### ISSUE TITLE
Clickable profiles confusion

### ISSUE THREAD

**Issue by mirabilos** [feditext/feditext#101]
The regression that mentions in a post weren’t clickable to lead to the profile was fixed, however not completely correctly.

In https://toot.mirbsd.org/@mirabilos/statuses/01H4DQTH9J2ZTCM8ZPFETA7AFJ and https://toot.mirbsd.org/@mirabilos/statuses/01H4DXAEEWDSM3W8HY1SFJ8E4T there’s two mentions of accounts with the same localpart and different domain. In FediText (as opposed to MetaText and Semaphore/Pinafore), clicking on either leads always to the first profile of them, so I guess you’re hashing by localpart only or something?

Ideally, in my eyes, do display the domain. Perhaps always, as a preference, in just ever so slightly smaller font. Perhaps if just localpart is not unique, though that could lead to confusion why it’s not always shown.

**Comment by VyrCossont** [comment]
Can you please post the HTML of those two statuses in here? I can't see either of them from either the web UI (normal for GtS unlisted posts) or by fetching them through my instance's search.

**Comment by mirabilos** [comment]
Dixi quod…

> 01H4DQTH9J2ZTCM8ZPFETA7AFJ | <p><span class="h-card"><a ***@***.***" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> <span class="h-card"><a ***@***.***" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> hmm, mal sehen, ob das überhaupt mit meinem GtS sauber föderiert, hatte da den anderen Tag Probleme mit</p>

By the way, replying to this toot in FediText (like in MetaText)
had the IDs of the accounts to reply two in random order, instead
of the one of the post I replied to first, then all others in the
same order as in that post (like e.g. Pinafore does).

bye,
//mirabilos
-- 
16:47⎜«mika:#grml» .oO(mira ist einfach gut....)      23:22⎜«mikap:#grml»
mirabilos: und dein bootloader ist geil :)    23:29⎜«mikap:#grml» und ich
finds saugeil dass ich ein bsd zum booten mit grml hab, das muss ich dann
gleich mal auf usb-stick installieren	-- Michael Prokop über MirOS bsd4grml

**Comment by mirabilos** [comment]
Vyr Cossont dixit:

>Can you please post the HTML of those two statuses in here? I can't see
>either of them from either the web UI (normal for GtS unlisted posts)
>or by fetching them through my instance's search.

Oh, I had hoped the latter would work, but, ok.

gotosocial=# SELECT id,content FROM statuses WHERE statuses.id IN ('01H4DQTH9J2ZTCM8ZPFETA7AFJ', '01H4DXAEEWDSM3W8HY1SFJ8E4T');                                                                                                                id             |                                                                                                                                                                                                                                    content
----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 01H4DQTH9J2ZTCM8ZPFETA7AFJ | <p><span class="h-card"><a ***@***.***" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> <span class="h-card"><a ***@***.***" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> hmm, mal sehen, ob das überhaupt mit meinem GtS sauber föderiert, hatte da den anderen Tag Probleme mit</p>
 01H4DXAEEWDSM3W8HY1SFJ8E4T | <p><span class="h-card"><a ***@***.***" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> <span class="h-card"><a ***@***.***" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> test 2 für nen Client-Bug</p>
(2 rows)

Thanks,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Comment by VyrCossont** [comment]
I'm going to need the exact HTML including well-formed and uncensored WebFinger URLs for the mentions to have a chance of debugging this. This isn't something I could paste into a parser test. You could replace usernames and domains with structure-and-syntax-preserving replacements like `username1`, `username2`, `domain1.tld`, `domain2.tld`.

**Comment by mirabilos** [comment]
Oh, I blame GitHub for censoring these things. I put them correctly in in the eMail.

Let’s try again…

```
Vyr Cossont dixit:

>Can you please post the HTML of those two statuses in here? I can't see
>either of them from either the web UI (normal for GtS unlisted posts)
>or by fetching them through my instance's search.

Oh, I had hoped the latter would work, but, ok.

gotosocial=# SELECT id,content FROM statuses WHERE statuses.id IN ('01H4DQTH9J2ZTCM8ZPFETA7AFJ', '01H4DXAEEWDSM3W8HY1SFJ8E4T');                                                                                                                id             |                                                                                                                                                                                                                                    content
----------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 01H4DQTH9J2ZTCM8ZPFETA7AFJ | <p><span class="h-card"><a href="https://octodon.social/@Kadsenchaos" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> <span class="h-card"><a href="https://blahaj.zone/@Kadsenchaos" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> hmm, mal sehen, ob das überhaupt mit meinem GtS sauber föderiert, hatte da den anderen Tag Probleme mit</p>
 01H4DXAEEWDSM3W8HY1SFJ8E4T | <p><span class="h-card"><a href="https://blahaj.zone/@Kadsenchaos" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> <span class="h-card"><a href="https://octodon.social/@Kadsenchaos" class="u-url mention" rel="nofollow noreferrer noopener" target="_blank">@<span>Kadsenchaos</span></a></span> test 2 für nen Client-Bug</p>
(2 rows)

Thanks,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999
```

Does this arrive better?

**Comment by VyrCossont** [comment]
Yes, thank you.

**Comment by VyrCossont** [comment]
Coming back to this: still a problem in the current build. Investigating. Confirmed that nothing is happening in the backend; loading https://toot.mirbsd.org/@mirabilos/statuses/01H4DQTH9J2ZTCM8ZPFETA7AFJ on a Glitch or GtS server I have access to works fine in the Glitch or Semaphore web GUIs, so it's 100% a Feditext bug.

**Comment by VyrCossont** [comment]
Found it. The `tag` and `accountId` patterns in `NavigationService` don't handle this case, and should be removed, as they've been obsoleted by our new semantic HTML link class recognition anyway.

**Comment by VyrCossont** [comment]
Fixed in build 70.
