### ISSUE TITLE
Link previews don’t have a fixed image size

### ISSUE THREAD

**Issue by evieluvsrainbows** [feditext/feditext#103]
This bug is not exclusive to Feditext, it was also an issue in Metatext before it was discontinued due to lack of maintainers. Basically, link previews in posts do not have a fixed image size and instead resort to setting the image size to i believe the primary image’s exact dimensions. attached are a couple screenshots showing what i mean.

![image](https://github.com/feditext/feditext/assets/1617100/11c9dff9-fc58-41ff-aedb-f9344f8d584f)

![image](https://github.com/feditext/feditext/assets/1617100/6eb3e15f-d309-4cf4-88ab-e172d1ea1013)

**Comment by VyrCossont** [comment]
Probably content hugging priority on the card's labels. Should switch to fully constrained layout from explore view cards.
