### ISSUE TITLE
Handle fatal network request errors

### ISSUE THREAD

**Issue by evieluvsrainbows** [feditext/feditext#104]
I have no clue what this is about, but this issue happened in Metatext as well, where whenever you go in and out of the app, occasionally an Alert dialog will pop up saying “cancelled” and nothing else. I don’t know what this bug is about or what’s causing it, though.

![image](https://github.com/feditext/feditext/assets/1617100/5f0035b0-8146-4691-818a-c2368e11db13)

**Comment by VyrCossont** [comment]
I've hit this one a few times as well, but can't repro it yet. Wish there was a way to annotate HTTP requests (this is almost certainly related to an HTTP request) with user actions to see what caused an error message.

**Comment by VyrCossont** [comment]
Added HTTP request error annotation today with 45be56856f7d2dde343a61dc86ec57efbc796798 and @rrgeorge has already provided us with two relevant samples:

#### timeout error

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 324
  },
  "app" : {
    "build" : "59",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "The request timed out.",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.5.1"
  },
  "title" : "NSURLError",
  "type" : "NSURLError"
}
```

#### cancelled error

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 324
  },
  "app" : {
    "build" : "59",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "cancelled",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.5.1"
  },
  "title" : "NSURLError",
  "type" : "NSURLError"
}
```

Some `NSURLError`s should either retry the request or abandon it. Which one is situational, and we could probably annotate `NSURLError` better, but these are likely to be timeline-related errors where retrying once or twice for a cancelled `GET` request is safe.

**Comment by VyrCossont** [comment]
1f10bfa0df796816a185970719c3fbbdeb7eeeb6 adds annotations for `URLError`, including the background task cancellation reason if available.

**Comment by VyrCossont** [comment]
We're not getting a cancellation reason with the extended logging either. That said, all of them have been timeline-related GET requests like this one, which we can safely retry.

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 324
  },
  "app" : {
    "build" : "61",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "code" : -999,
    "method" : "GET",
    "name" : "cancelled",
    "requestLocation" : {
      "file" : "ServiceLayer/TimelineService.swift",
      "function" : "request(maxId:minId:search:)",
      "line" : 75
    },
    "url" : "https://raphus.social/api/v1/timelines/home"
  },
  "message" : "GET https://raphus.social/api/v1/timelines/home\n\ncancelled",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.5.1"
  },
  "title" : "AnnotatedURLError",
  "type" : "AnnotatedURLError"
}
```

**Comment by bdube** [comment]
I'm getting these pretty consistently today. I'm tethered to my phone with bluetooth.

```
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 370
  },
  "app" : {
    "build" : "64",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "code" : -1005,
    "method" : "GET",
    "name" : "networkConnectionLost",
    "requestLocation" : {
      "file" : "ServiceLayer/TimelineService.swift",
      "function" : "request(maxId:minId:search:)",
      "line" : 93
    },
    "url" : "https://gotgoat.com/api/v1/timelines/home"
  },
  "message" : "GET https://gotgoat.com/api/v1/timelines/home\n\nnetworkConnectionLost",
  "system" : {
    "idiom" : "pad",
    "model" : "iPad",
    "name" : "iPadOS",
    "version" : "16.5.1"
  },
  "title" : "AnnotatedURLError",
  "type" : "AnnotatedURLError"
}
```

**Comment by VyrCossont** [comment]
On second thought: rather than retry, I think we need to let these fail, just more quietly, so that's what I've started doing for GET requests that fail due to cancelled requests or timeouts. 

@bdube Build 64 doesn't include `networkConnectionLost` as a reason to quietly fail but perhaps the next one should, since even retrying wouldn't help. Do your network errors happen when you leave and return to the app, or while it's in the foreground?

I've seen some apps display a modal about lost connectivity, but personally, I've never found those to be terribly useful, since my phone already displays the connection state.

**Comment by bdube** [comment]
@VyrCossont I think each time I saw it, I was returning to the app from something else. I'll try to keep better track next time.

**Comment by VyrCossont** [comment]
Another user reported this in #151 with a totally offline device (Airplane Mode) and the `notConnectedToInternet` code. We can use [`NWPathMonitor`](https://developer.apple.com/documentation/network/nwpathmonitor) to provide more helpful UI. I've seen at least one StackOverflow post mentioning that poor UI on network failures got an app dinged in App Store review.

**Comment by VyrCossont** [comment]
d3c0f915a7a86dc2c443ade427b118933d2ef4ab provides a better experience when the user isn't connected:

![a Feditext toast (transient alert at top of screen) stating "No Internet connection"](https://github.com/feditext/feditext/assets/26195552/1b958871-0091-4c09-bfe0-ef3622c959d1)

Didn't end up using `NWPathMonitor`, but the toast banners don't get in the way like modals even if multiple errors occur, which is guaranteed for network stuff.
