### ISSUE TITLE
Previously displayed thumbnails may be shown under posts that are missing media

### ISSUE THREAD

**Issue by vivlim** [feditext/feditext#107]
**Describe the bug**
I am running Mastodon with a [custom modification that rejects media from remote users that aren’t explicitly followed by a local user.](https://github.com/glitch-soc/mastodon/commit/857fac650c46e946960918a77fcf360372ed58b8)

When a Mastodon instance is missing a copy of a post’s media, sometimes other thumbnails are shown instead of nothing. My uninformed guess is that this seems to have something to do with the reuse of previously-allocated thumbnail images while scrolling down the timeline. I figure that normally cases, the thumbnail buffer is supposed to be overwritten with a new thumbnail, but that doesn’t happen if the image is just missing.

This is *very* confusing, although i’ve mostly gotten used to it and have been living with it for the half a year or so i’ve been using feditext. 

**To Reproduce**
1. Use an instance with the linked modification. 
2. Encounter missing remote media while scrolling.
3. Sometimes instead of showing a blank space with a 🔗 icon, a different post’s thumbnail will be shown.

**Expected behavior**
Thumbnails only show up for posts that have media, and always match the media that will be shown when tapped. 

**Screenshots**

![IMG_3558](https://github.com/feditext/feditext/assets/1565930/3cb5d93a-81cc-4733-951e-24b1e1e2df66)
![IMG_3559](https://github.com/feditext/feditext/assets/1565930/d8d38336-0c3b-420f-b084-f67712e47bd3)

**(please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.5.1 (c)
 - App Version 1.7.2 (61)

**Additional context**
I think I am literally the only person affected by this, because none of the other people on my instance use iOS, and as far as I know, nobody else is using this modification. While I would really appreciate this being fixed I would also understand it not being fixed.

Ideally I’d like to be able to have Feditext actually fetch the media from the remote instance (perhaps on demand, or behind a setting because this could be a privacy concern) but that’s probably a stretch for something that seems incredibly niche like this (although maybe there are other fediverse servers that behave like this??? no idea.)

**Comment by VyrCossont** [comment]
Incredible demo screenshots. I'll take a look tomorrow; it's almost certainly a cell reuse bug, as you say.

**Comment by weirdofhermiston** [comment]
I'm also having this issue but don't know if my instance is using the modification. I'm not an instance admin. It did this for an audio post from a different user. Bird photo is first post, which got added to the audio thumbnail.

![IMG_0504](https://github.com/feditext/feditext/assets/142334696/02e5aa7f-08e7-4469-a367-887952d97a45)

![IMG_0503](https://github.com/feditext/feditext/assets/142334696/2a1f1bf9-2678-4678-96fe-0fead9ecc728)

**Comment by VyrCossont** [comment]
https://firefish.social/notes/9in2xxadowopndso triggers this bug when logged into Mastodon instance infosec.exchange.

**Comment by VyrCossont** [comment]
We have ample confirmation that this can happen on any server, so I'm adding it to milestone 1.7. My guess is that the app isn't handling an error during media load correctly.

**Comment by VyrCossont** [comment]
5c0ec187ac14d165d5e2855ba4c26c857979537e (build 87) largely reverts media attachment views to their Metatext versions, removing view pre-allocation and recycling, which should prevent issues like out-of-place thumbnails, and may also improve timeline scrolling performance. I'm not sure if it affects the off-centered images with blurred edges yet.

This may re-introduce the animation glitches I was attempting to fix with the original changes. They didn't repro for me on my iPhone 6S+ or my iPhone 12 Pro Max, but I'm not sure I remember all the repro instructions.

**Comment by VyrCossont** [comment]
The easiest way to test this was with audio posts next to image posts, and I can't repro that any more. I believe not recycling fixed it.
