### ISSUE TITLE
App crash on load when touching timeline button

### ISSUE THREAD

**Issue by joan7770** [feditext/feditext#108]
**Describe the bug**
Upon opening the app it can crash when double tapping the timeline button if the app is still loading from a cold start (not recently open)

**To Reproduce**
1. Make sure no app cache is in the device memory. (Not in multitask and not open recently)
2. Open the app
3. Tap or double tap timeline while app is still starting up.
4. App crash

**Expected behavior**
Timeline refresh after app startup

**Screenshots**

[Screen recording](https://bunni.social/@joan/110756476315185613)

**(please complete the following information):**
 - Device: iPhone SE 2020 (2nd gen)
 - OS: iOS 16.5.1 (20F75) with rapid security response 16.5.1 (c) (20F770750d)
 - App Version TestFlight 1.7.2 (61)

**Additional context**
Was able to reproduce issue 3 times. Issue does not occur after app has recently been open nor from app switching.

**Comment by joan7770** [comment]
Added screen recording to issue description.

**Comment by VyrCossont** [comment]
Thank you for the detailed repro!

**Comment by VyrCossont** [comment]
Confirmed. You have to tap it *really fast* to repro on an iPhone 11 but it's doable.

**Comment by VyrCossont** [comment]
I can no longer repro this, on simulator, iPhone 6s+ (iOS 15), or iPhone 12 Pro Max (iOS 17). On the chance that it was some sort of text rendering bug, I've tried with both WebKit and Siren. Feel free to reopen this if it happens again, but I'm going to assume some change in the past few months fixed it.
