### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by dtfleetwood** [feditext/feditext#109]
Was asked to post these if I hit them.  Opened app today and this popped right up.

{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 324
  },
  "app" : {
    "build" : "62",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "code" : -1001,
    "method" : "GET",
    "name" : "timedOut",
    "requestLocation" : {
      "file" : "ServiceLayer/TimelineService.swift",
      "function" : "request(maxId:minId:search:)",
      "line" : 75
    },
    "url" : "https://calckey.social/api/v1/timelines/home"
  },
  "message" : "GET https://calckey.social/api/v1/timelines/home\n\ntimedOut",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.5.1"
  },
  "title" : "AnnotatedURLError",
  "type" : "AnnotatedURLError"
}

**Comment by VyrCossont** [comment]
Thank you! This is the same underlying issue as #104: a timeline request isn't finished when the app goes into background, and should be retried.
