### ISSUE TITLE
Follow an hashtag from the search results

### ISSUE THREAD

**Issue by theppn** [feditext/feditext#110]
**Is your feature request related to a problem? Please describe.**
Right now it is a bit awkward because when you search for an hashtag and maybe plan to follow it, there is no obvious way to do it from the search results. You have to back out all the way out of the explore tab and go to followed hashtags on your profile menu to add it manually. 

**Describe the solution you'd like**
A follow button on the top right directly on the timeline view for the hashtag.

**Comment by VyrCossont** [comment]
I agree that this *should* work. The search API returns the [`following`](https://docs.joinmastodon.org/entities/Tag/#following) flag on `Tag` objects (assuming the backend supports it), so we have the info on whether to show that button and what state it should be in. I'm not sure if this is a regression or an oversight.

**Comment by VyrCossont** [comment]
This turned out to be a regression: we weren't keeping a reference that we should have been keeping. Tag timelines should now have the upper right corner button again.
