### ISSUE TITLE
Feditext should notify or display a notice when an account has moved

### ISSUE THREAD

**Issue by theppn** [feditext/feditext#112]
**Is your feature request related to a problem? Please describe.**
When an account has moved to a new account or a new server, the web UI usually displays a notice about it. Feditext does not provide any information about that to the user.

**Describe the solution you'd like**
Ideally Feditext should send a notification to inform the user about the move and suggest to follow the new account.

**Describe alternatives you've considered**
An alternative would be to at least display a similar notice to the web version when visiting the profile "X has indicated that their new account is now...".

**Additional context**
An example of an account that moved: https://mastodonapp.uk/@mdf200.

**Comment by VyrCossont** [comment]
> Ideally Feditext should send a notification to inform the user about the move and suggest to follow the new account.

This is out of scope for a client: your server is supposed to handle migrations. But I can add that notice to migrated profiles with a button to navigate to the new profile.
