### ISSUE TITLE
Glitch-soc instance missing features in app

### ISSUE THREAD

**Issue by puzzler995** [feditext/feditext#115]
**Describe the bug**
My instance, cutie.city, runs a slight deviation from glitch-soc, and since the updates to filter features based on instance software I'm missing things like the DM page and lists. 

**Expected behavior**
Access to mastodon features on a masto fork 

**Screenshots**

![image](https://github.com/feditext/feditext/assets/943558/ae2f0888-8d70-4d72-8dc8-7abfccb2bdb1)

**(please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: iOS 16.5.1 c 
 - App Version: still occurring on build 64

**Additional context**
The version on the instance's web about page is v4.1.3+glitch+cutiecity

**Comment by VyrCossont** [comment]
We need to use a relaxed version parser on instances like cutie.city that don't have valid SemVer versions. As long as we can get numeric major, minor, and patch, it's fine.

@puzzler995 There's a workaround at the bottom of Feditext's preferences: scroll down to Advanced, set API compatibity mode to "Enable all API calls, attempt error recovery", and tap the red refresh button. This will enable those features until I fix this in the next build.

**Comment by VyrCossont** [comment]
This should be fixed in the next build.

**Comment by VyrCossont** [comment]
@puzzler995 If you update to yesterday's build and switch off API compatibility mode, does everything work properly?

**Comment by puzzler995** [comment]
It does, thank you!
