### ISSUE TITLE
Firefish.social throws HTTP 401 Unauthorized after login

### ISSUE THREAD

**Issue by maique** [feditext/feditext#121]
No issues with a Mastodon account so far, but Firefish.social throws an error after accepting credentials. 

iPhone 13 Pro, iOS 17 Public Beta, Feditext latest beta release. 

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 370
  },
  "app" : {
    "build" : "64",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "HTTP Error: 401",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.0"
  },
  "title" : "HTTPError",
  "type" : "HTTPError"
}
```

**Comment by VyrCossont** [comment]
Thanks for the report. I have a firefish.social login and can test this directly.

**Comment by VyrCossont** [comment]
There's something wrong with firefish.social specifically, related to its Mastodon API endpoints. The instance info API https://firefish.social/api/v1/instance does not load for me. I've let the instance admin know. Other Firefish instances such as infosec.town don't have this problem, so it's not a Feditext bug.

**Comment by beanymax** [comment]
Not sure if this is related or new. Will not sign in to Firefish.social, other calckey, akkoma and mastodon accounts all ok:


{
  "alertLocation" : {
    "file" : "ViewModels/AddIdentityViewModel.swift",
    "function" : "addIdentity(kind:)",
    "line" : 110
  },
  "app" : {
    "build" : "70",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "method" : "GET",
    "reason" : "invalidStatusCode",
    "requestLocation" : {
      "file" : "MastodonAPI/NodeInfoClient.swift",
      "function" : "nodeInfo()",
      "line" : 21
    },
    "statusCode" : 500,
    "url" : "https://firefish.social/nodeinfo/2.1"
  },
  "message" : "GET https://firefish.social/nodeinfo/2.1\n\nHTTP Error: 500",
  "system" : {
    "idiom" : "pad",
    "model" : "iPad",
    "name" : "iPadOS",
    "version" : "16.6"
  },
  "title" : "HTTPError",
  "type" : "HTTPError"
}
