### ISSUE TITLE
Bumpy scrolling on multiple devices

### ISSUE THREAD

**Issue by a-oe** [feditext/feditext#122]
**Describe the bug**
Slightly bumpy scrolling on iPhone SE iOS 16.6.
Account on berlin.social. Smoothly scrolling in several other iOS apps.

**(please complete the following information):**
 - Device: iPhone SE
 -  OS: iOS 16.6
 - App Version 1.7.2 (64)

**Comment by VyrCossont** [comment]
@a-oe Thanks for the report. Looks like berlin.social is a standard Mastodon instance. Is your iPhone SE a 1st generation (2016), 2nd generation (2020), or 3rd generation (2022) model?

**Comment by a-oe** [comment]
3rd generation (2022) model. 

> 
> Am 28.07.2023 um 19:02 schrieb Vyr Cossont ***@***.***>:
> 3rd generation (2022) model

**Comment by SamirTalwar** [comment]
I'm having the same issue on an iPhone 11 Pro Max.

**Comment by jmd-aKBar** [comment]
Similar "issue" noticed on iPhone 11 Pro with an account on the ioc.exchange server.

**Comment by egeesin** [comment]
Here's current scroll performance comparison between Safari and Feditext (1.7.2 (69)) on my iPhone 7 (iOS 15.5)

https://github.com/feditext/feditext/assets/8004972/8a1ee92f-7b52-4297-ba06-40f36f79d731

**Edit:** Forgot to include Metatext 1.7.1:

https://github.com/feditext/feditext/assets/8004972/487b58bd-1abd-4da0-bd8d-8e33cd7ea4ab

**Comment by dbrewood** [comment]
Same issue here.

**Comment by outlaw-dame** [comment]
Running iOS 17 dev beta iOS 17.0 (21A5312c)
On a 14 Pro Max. 
Experiencing the same issue with choppy scrolling

**Comment by drsheepchase** [comment]
Same issue. Very noticeable compared to other apps.

iOS 16.6, iPad OS 16.6

IPhone 14 Pro
IPad Pro 12.9 inch 4th gen

**Comment by VyrCossont** [comment]
This is the next big bug on my list, after #124.

**Comment by wdejaeghere** [comment]
iPhone 13 mini, iOS 17.0 beta (latest).

The bumpy scrolling makes using the app impossible.
The interface is very laggy. It takes seconds before a swipe makes the screen scroll, or whatever action was intended.

Not sure if this is the same issue, or something different.

**Comment by meljoann** [comment]
Can confirm it's also bumpy on ios 16.6.1, iPhone 11, Feditext 1.7.2

I remember Metatext was the same,too.

**Comment by VyrCossont** [comment]
I realize this bug has been open a while but anyone in this thread, please let me know if scrolling feels any different with the most recent build. The fix for #107 should have also removed a source of stutter.

**Comment by VyrCossont** [comment]
Presumed fixed by the fix to #107.

**Comment by outlaw-dame** [comment]
Thank you
