### ISSUE TITLE
Firefish: SQLite error 19: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by norbsmaq** [feditext/feditext#124]
**Describe the bug**
When I opened the app, I received a JSON/SQLite error.  I tried force closing and reopening and the error was still there, however later on I tried again and the error was gone.  I am using the Firefish/Calckey instance at infosec.town.

**To Reproduce**
1. Open the app

**(please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.6
 - App Version 1.7.2

**Additional context**
JSON error information here:

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 370
  },
  "app" : {
    "build" : "65",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "SQLite error 19: FOREIGN KEY constraint failed - while executing INSERT INTO \"statusRecord\" (\"id\", \"uri\", \"createdAt\", \"editedAt\", \"accountId\", \"content\", \"visibility\", \"sensitive\", \"spoilerText\", \"mediaAttachments\", \"mentions\", \"tags\", \"emojis\", \"reblogsCount\", \"favouritesCount\", \"repliesCount\", \"application\", \"url\", \"inReplyToId\", \"inReplyToAccountId\", \"reblogId\", \"poll\", \"card\", \"language\", \"text\", \"favourited\", \"reblogged\", \"muted\", \"bookmarked\", \"pinned\", \"reactions\") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.6"
  },
  "title" : "DatabaseError",
  "type" : "DatabaseError"
}
```

**Comment by VyrCossont** [comment]
I've also gotten this error once or twice on infosec.town. I wish GRDB would tell us *which* foreign key constraint failed, but there aren't too many candidates: maybe Firefish is pulling some funny business with reblog IDs.

**Comment by VyrCossont** [comment]
Another user reported this on IceShrimp in #138. Safe to say we have a pattern.

**Comment by josharky** [comment]
I've posted a link to #124 in the Iceshrimp dev matrix. I'm hoping former Calckey maintainer April might be able to help you solve this issue on the FF/IS side.

**Comment by josharky** [comment]
This has now also been [added as a bug report](https://iceshrimp.dev/iceshrimp/iceshrimp/issues/53) by a dev over on the Iceshrimp repo.

**Comment by aprilthepink** [comment]
I dont have ios, any way for me to debug this?

**Comment by VyrCossont** [comment]
@CutestNekoAqua not really: our macOS build isn't usable yet. And if you don't have a Mac, *definitely* not.

I suspect this has something to do with a post structure I've only ever seen from Calckey-derived backends, which is a post that contains a reblog that itself contains a reblog, and that our DB code needs to either store incoming posts recursively. However, I'm not sure *why* a reblog needs to contain a reblog, or what the expected display behavior would be.

Does Calckey intentionally do the Tumblr thing where you can reblog someone else's reblog? How far can they nest? The Mastodon, Akkoma, and GtS APIs definitely do not ever produce this kind of structure, so I'm thinking it may be a bug in CK/FF/IS's Mastodon API layer.

**Comment by aprilthepink** [comment]
Yes that behavior is intentional:tm: as the logic is: a quote reblog is a own post and that can be quoted again. We are talking quotes here right?

**Comment by VyrCossont** [comment]
@CutestNekoAqua that question actually leads me to my followup question, which is: quoting posts have the same post in both `quote` and `reblog` fields. Is this intentional? Most Mastodon API clients I've tested do not display text from any post that has a non-null `reblog`, so this seems off; quoting posts would have their own text ignored.

Also, is there a server-side cap on how deep these structures can be? Because a post chain would grow in object size either linearly with every reblog or exponentially every time it's quoted, and if someone hasn't used that for DoS fun times yet…

**Comment by VyrCossont** [comment]
@CutestNekoAqua actually lemme construct some example posts on a real instance and get back to you, just in case I'm talking out of my ass

**Comment by norbsmaq** [comment]
I received the error again just now. Pasting the JSON in case it’s useful. It may be the same as before. 

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 370
  },
  "app" : {
    "build" : "68",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "SQLite error 19: FOREIGN KEY constraint failed - while executing `INSERT INTO \"statusRecord\" (\"id\", \"uri\", \"createdAt\", \"editedAt\", \"accountId\", \"content\", \"visibility\", \"sensitive\", \"spoilerText\", \"mediaAttachments\", \"mentions\", \"tags\", \"emojis\", \"reblogsCount\", \"favouritesCount\", \"repliesCount\", \"application\", \"url\", \"inReplyToId\", \"inReplyToAccountId\", \"reblogId\", \"poll\", \"card\", \"language\", \"text\", \"favourited\", \"reblogged\", \"muted\", \"bookmarked\", \"pinned\", \"reactions\") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.6"
  },
  "title" : "DatabaseError",
  "type" : "DatabaseError"
}
```

**Comment by nfrede** [comment]
I also got a similar error when trying to view the “firefish@fedi.software” profile. 

My account is on the infosec.town instance which is running 1.0.4 of Firefish atm. 

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 370
  },
  "app" : {
    "build" : "70",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "SQLite error 19: FOREIGN KEY constraint failed - while executing `INSERT INTO \"statusRecord\" (\"id\", \"uri\", \"createdAt\", \"editedAt\", \"accountId\", \"content\", \"visibility\", \"sensitive\", \"spoilerText\", \"mediaAttachments\", \"mentions\", \"tags\", \"emojis\", \"reblogsCount\", \"favouritesCount\", \"repliesCount\", \"application\", \"url\", \"inReplyToId\", \"inReplyToAccountId\", \"reblogId\", \"poll\", \"card\", \"language\", \"text\", \"favourited\", \"reblogged\", \"muted\", \"bookmarked\", \"pinned\", \"reactions\") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.0"
  },
  "title" : "DatabaseError",
  "type" : "DatabaseError"
}
```

**Comment by VyrCossont** [comment]
Updated title to make it easier to find for other reporters. This one is next on my important weird bug list.

**Comment by VyrCossont** [comment]
Almost got this one nailed down. Tomorrow, probably.

**Comment by VyrCossont** [comment]
Should be fixed in the next build. Shipping something *useful* on top of that required implementing very basic quote post support, since otherwise those quote posts just look like reblogs and don't display correctly.
