### ISSUE TITLE
The "Edit Profile" button links to the users' domain, not the instance domain

### ISSUE THREAD

**Issue by SamirTalwar** [feditext/feditext#136]
**Describe the bug**

My Mastodon profile is "samir@functional.computer", but the Mastodon instance is "mastodon.functional.computer". The _Edit Profile_ button should link to the latter.

**To Reproduce**
1. Click _Edit Profile_
2. Watch as an arbitrary web page is loaded

**Expected behavior**

The correct page is loaded.

**(please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 16.6
 - App Version 1.7.2 (66)

**Comment by VyrCossont** [comment]
Should be fixed in the next release.

**Comment by bdube** [comment]
My apologies. This was closed by mistake in a branching accident.

**Comment by VyrCossont** [comment]
@SamirTalwar Can you confirm if this is fixed for you? I don't have access to a test instance with a different `LOCAL_DOMAIN` and `WEB_DOMAIN`.

**Comment by SamirTalwar** [comment]
Yup, all fixed! Thank you. 😊
