### ISSUE TITLE
AnnotatedDecodingError

### ISSUE THREAD

**Issue by hpux735** [feditext/feditext#144]
**Describe the bug**
After the onboarding follow, and logging into an 14.0.0-dev19-hk25 instance I got the above error. 

**To Reproduce**
1. Log onto an instance with the given software
2. Click on either home, local, or federated
4. The error should appear after a short time. 

**Expected behavior**
Ideally, the timeline would load. 

**(please complete the following information):**
 - Device: iPhone SE Gen something or other
 - OS: iOS 16.5.1
 - App Version 1.7.2 (67)

**Additional context**
I will DM with the JSON

**Comment by VyrCossont** [comment]
This is the same issue as #143 and will get patched tonight or tomorrow. Thanks for the report!

**Comment by hpux735** [comment]
ooof, that's embarrasing.  I tried to look for dupes, but clearly I didn't do a great job.  Thanks so much!
