### ISSUE TITLE
Set up metatext-apns push notifications

### ISSUE THREAD

**Issue by bdube** [feditext/feditext#15]
https://github.com/metabolist/metatext-apns

**Comment by bdube** [comment]
The sinatra app needed a minor change to work with newer gem dependencies. Notifications are coming through now.

**Comment by rrgeorge** [comment]
Should this be working on the TestFlight version? I’m not seeing any push notifications for FediText.

**Comment by bdube** [comment]
Yes, should be working. The most recent notifications to flow through the endpoint were 8 minutes ago.

Which TestFlight build do you have?

**Comment by rrgeorge** [comment]
40

**Comment by bdube** [comment]
Ok, I'm cleaning up the workflows a bit and starting a new build for TestFlight. I got a notification just now with build 41, but I see that build came from a different workflow.

**Comment by rrgeorge** [comment]
Did some investigating and I think somehow it was registered with the old metabolist endpoint. I logged out and logged back in, and now I see the correct endpoint.
