### ISSUE TITLE
Fail more gracefully upon loss of Internet connection 

### ISSUE THREAD

**Issue by sporklet** [feditext/feditext#151]
**Describe the bug**
When performing an action in Feditext that requires an Internet connection that drops out, up pops a modal “notConnectedToInternet” dialogue box. Feditext should fail more gracefully and, depending on the action, try it again automatically when the connection is restored. 

**To Reproduce**
1. Disable Wi-Fi, or enable Airplane Mode
2. Pull to refresh the timeline
3. See error

**Expected behavior**
Perhaps a banner message at the top of the window saying “Offline,” changing to “Back online. Retrying…”

**Screenshots**

**(please complete the following information):**
 - Device: iPad Pro (2018)
 - OS: iPadOS 16.6
 - App Version 1.7.2
[notConnectedToInternet.json.txt](https://github.com/feditext/feditext/files/12234512/notConnectedToInternet.json.txt)

**Comment by VyrCossont** [comment]
Thanks for the report! Agree with the conclusion, we need better UI for totally non-recoverable errors that require the user to do something like fix their internet connection. #104 is pretty much the same issue, so we'll track it there.
