### ISSUE TITLE
Firefish and Hajkey choke if pinned parameter is present 

### ISSUE THREAD

**Issue by VyrCossont** [feditext/feditext#152]
If the `pinned` parameter is present for a https://docs.joinmastodon.org/methods/accounts/#statuses call, regardless of value, Firefish (`development` branch) and Hajkey (whatever blahaj.zone is running today) will return an empty list.

This is definitely a server-side bug, since I already have a patch that fixes it for Firefish, but it's also one we can work around by not sending boolean parameters for this call when their values would be false.

**Comment by VyrCossont** [comment]
- Iceshrimp: https://iceshrimp.dev/iceshrimp/iceshrimp/pulls/68
- Firefish: https://git.joinfirefish.org/firefish/firefish/-/merge_requests/10549

**Comment by bdube** [comment]
My apologies. This was closed by mistake in a branching accident.

**Comment by VyrCossont** [comment]
No worries. This has been fixed in both Feditext and both affected servers.
