### ISSUE TITLE
Fave and Boost buttons not working for Akkoma

### ISSUE THREAD

**Issue by belatedly** [feditext/feditext#153]
**Describe the bug**
When I press the fave and boost buttons I can see the press is recognized as the icon color changes slightly, but nothing happens. It does recognize that I’ve faved or boosted a post from the web though, and has them colored in appropriately. 

**To Reproduce**
1. Log into an Akkoma account
2. Click on fave or boost on a post

**Expected behavior**
The post should be faved or boosted. 

**Screenshots**
https://github.com/feditext/feditext/assets/63966511/0ca9ecdc-5361-40ad-9a2d-9ec29d6d64f2

**(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.5.1 (c)
 - App Version: 1.7.2

**Additional context**
Akkoma version: [3.9.3-0-g9d7c877](https://akkoma.dev/AkkomaGang/akkoma/commit/9d7c877)

**Comment by VyrCossont** [comment]
Thanks for the report! I'll take a look on my Akkoma test account.

**Comment by VyrCossont** [comment]
@alcapurrias I can't repro this on the Akkoma 3.9.3 server I have access to (infosec.place). Followup questions:

- Does it happen consistently, every time?
- Is there any error message, or does it just fail? (from the video, it doesn't seem like there's ever an error)
- Does replying work?
- Does it still happen after you log out of Akkoma in the app and log back in?

**Comment by belatedly** [comment]
I am so sorry, it’s 100% user error. I had turned on the double tap to boost and favorite options and completely forgot. I just figured it out when I tested after logging out and back in and got a little hasty with my taps 🤦‍♀️

**Comment by VyrCossont** [comment]
Oh, right on, best kind of bug. Thanks for following up!
