### ISSUE TITLE
Allow emoji (and someday instance specific) reactions to posts

### ISSUE THREAD

**Issue by hpux735** [feditext/feditext#156]
**Describe the solution you'd like**
It would be nice if there was a reaction picker button next to the ⭐️ button beneath a toot. It could look basically like the picker from Slack (or discord, or whatever) 

<img width="375" alt="image" src="https://github.com/feditext/feditext/assets/1170900/72f7cf9c-5961-4e0c-a753-707c94d85d38">

**Describe alternatives you've considered**
I think the only other alternative would be to share the post to safari, assuming you’re logged in, to add a reaction there. 

**Additional context**
This is a “nice to have” of course. I’ve been using Feditext for a few hours, and it will certainly be my daily driver. It’s honestly fantastic. I’ve just got a need … a need for … more … _reactions_

**Comment by VyrCossont** [comment]
![Feditext screenshot with a React post menu item for adding emoji, and showing emoji reactions under some posts](https://github.com/feditext/feditext/assets/26195552/20d359b1-5ce2-4df1-8aef-b9e85ff78182)

Good news, we already have this!

Bad news for you specifically: your instance doesn't support it yet. You need to be on Firefish 1.0.4, Iceshrimp development, Akkoma, or a Glitch instance with glitch-soc/mastodon#2221 applied. (I added the Mastodon-compatible emoji reactions API to Firefish and Iceshrimp myself.) When Hajkey rebases on Iceshrimp, they should pick this up, and then it'll work for you.

**Comment by hpux735** [comment]
Thanks!

**Comment by hpux735** [comment]
[Hajkey bug](https://codeberg.org/supakaity/hajkey/issues/18)
