### ISSUE TITLE
Voting on a poll doesn’t work with hajkey

### ISSUE THREAD

**Issue by hpux735** [feditext/feditext#160]
**Describe the bug**
I tried to vote on a poll and got an HTTP error. I’m on an instance that uses `14.0.0-dev19-hk25`

**To Reproduce**
1. Go to a poll
2. Click on an option
3. Click on “vote”
5. See error

**Expected behavior**
The poll vote should work

**(please complete the following information):**
 - Device: [e.g. iPhone SE gen something 
 - OS: 16.5.1
 - App Version 1.7.2 (69)

**Additional context**
JSON error:

```
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "events",
    "line" : 356
  },
  "app" : {
    "build" : "69",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "method" : "POST",
    "reason" : "invalidStatusCode",
    "requestLocation" : {
      "file" : "ServiceLayer/StatusService.swift",
      "function" : "vote(selectedOptions:)",
      "line" : 168
    },
    "statusCode" : 500,
    "url" : "https://xxx.xxx/api/v1/polls/0/votes"
  },
  "message" : "POST https://xxx.xxx/api/v1/polls/0/votes\n\nHTTP Error: 500",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.5.1"
  },
  "title" : "HTTPError",
  "type" : "HTTPError"
}
```

**Comment by VyrCossont** [comment]
Thanks @hpux735! I'll take a look at this next time I do a round of testing against Hajkey.

**Comment by VyrCossont** [comment]
No repro on Firefish. Think this is another Hajkey-specific bug.

**Comment by hpux735** [comment]
[Hajkey bug](https://codeberg.org/supakaity/hajkey/issues/19)
