### ISSUE TITLE
Block quote formatting overlaps other text 

### ISSUE THREAD

**Issue by olivvybee** [feditext/feditext#164]
**Describe the bug**
A post that contains a block quote and then more text below results in the quote formatting overlapping the other text.

**To Reproduce**
Create or find a post with a block quote in it (markdown `>` syntax) such as https://is-a.wyvern.rip/notes/9hzoaaedj12qcanc

**Expected behavior**
The text below the quote should have some space above it.

**Screenshots**

in the timeline:
![image](https://github.com/feditext/feditext/assets/661493/220e49a5-b6d2-4735-98de-eedd9d0a329e)

in the detail view:
![image](https://github.com/feditext/feditext/assets/661493/165d8027-145e-4b90-8072-40acddbb48f9)

How the post looks on the web:
![image](https://github.com/feditext/feditext/assets/661493/d4458793-9f88-40c8-af3d-fd8b73b00ed8)

**(please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.5.1 (c)
 - App Version: 1.7.2 (69)

**Additional context**
I wasn’t quite able to reproduce with a post of my own so potentially it’s a firefish specific issue. My instance is glitch-soc. although there isn’t a lot of space between the quote and the next text.

![image](https://github.com/feditext/feditext/assets/661493/40d73038-3c9e-4b90-8a14-54b539c3c317)

**Comment by bdube** [comment]
Thank you for the report. I'm going to mark this one as related to #48.

**Comment by VyrCossont** [comment]
Thanks for the report! This is indeed likely to be the same underlying problem as #48, but I hadn't seen the Firefish variation yet.

**Comment by VyrCossont** [comment]
AFAIK this is now impossible with Siren.
