### ISSUE TITLE
Prompt on media save still refers to app as "Metatext"

### ISSUE THREAD

**Issue by jmd-aKBar** [feditext/feditext#172]
**Describe the bug**
The prompt which pops up when asking for permission to save media in the Photo library still refers to the app as "Metatext". 

**To Reproduce**
1. Ensure Feditext doesn't already have media saving permissions
2. Try to save any media - photo/vid. 
3. Notice the text on the prompt for permissions. 

**Expected behavior**
Permission prompt should read "Feditext" on both the prompt sections. 

**Screenshots**
Attached here. [image](https://github.com/feditext/feditext/assets/3871861/943c5b7c-b73c-421e-8d17-063582faae69)

**(please complete the following information):**
 - Device: [e.g. iPhone 11 Pro]
 - OS: [e.g. iOS 16.6]
 - App Version [e.g. 1.7.2 (69)]

**Additional context**
This issue will be noticed only if you are trying to save media for the first time.

**Comment by VyrCossont** [comment]
Confirmed. Thanks for the report.

**Comment by VyrCossont** [comment]
Fixed in build 70.
