### ISSUE TITLE
Image smearing on some specific un-expanded images

### ISSUE THREAD

**Issue by VyrCossont** [feditext/feditext#185]
**To Reproduce**
1. Go to https://fedibird.com/@noellabo/110829937209608166 or thereabouts, in timeline view (like on `@noellabo`'s media tab)
2. Scroll up or down a bit
3. That image may have smearing on bottom or right edge
4. This is not consistent, may change with scrolling, might not work in search results (only timeline) and doesn't happen if the post is focused
5. But it is semi-repeatable with those images

**Screenshots**
![screnshot showing edge smearing](https://github.com/feditext/feditext/assets/26195552/6a6b5385-c96b-4cca-be6a-addda4d4075d)

**(please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 16.6
 - App Version: 1.7.2 (build 70)

**Comment by bdube** [comment]
I see this somewhat regularly with a wider band of smearing across the tops of images in my timeline.

- iPhone SE (2gen)
- iOS 16.6

**Comment by VyrCossont** [comment]
Oh, and since I forgot to include the server type in my report (I'll update the report templates soon): I saw this on Universeodon (Mastodon 4.1.5-novae). @bdube was this on your own instance?

**Comment by bdube** [comment]
Yes, I see it on my instance. It's Mastodon v4.1.6 with a patch to increase post character limit.

**Comment by rrgeorge** [comment]
I also see this randomly on mine (vanilla 4.1.6). Also some random image shifting. I always suspected it was something like the focal point is being applied to the image after it’s displayed.

**Comment by VyrCossont** [comment]
Suspect this is the same underlying bug as #107, hopefully also fixed by reverting to Metatext-era media attachment views. Adding to 1.7 milestone.

**Comment by VyrCossont** [comment]
Can't reproduce this one any more.
