### ISSUE TITLE
Have Explore tab mirror Timelines tab

### ISSUE THREAD

**Issue by FueledxJarritos** [feditext/feditext#192]
**Is your feature request related to a problem? Please describe.**
Had the app for a couple days now and have used it a decent bit, but I only just discovered it had a Trending Toots and Trending Links section

**Describe the solution you'd like**
It would be super cool to see the explore tab have 3 separate pages you can swipe between like the Timelines tab has for Home, Local, Federated, but for Hashtags, Links, and Toots. Or one for Accounts in addition to Hashtags?

![IMG_1157](https://github.com/feditext/feditext/assets/53276676/c47e8e8c-cf1b-40c5-bdb0-b3d1d094d1b1)
![IMG_1158](https://github.com/feditext/feditext/assets/53276676/055fa66e-cda0-40df-98e8-10f74f949cb2)

**Comment by VyrCossont** [comment]
Good news: This is on our roadmap for the next major version, 1.8. (See #76.) The current UI definitely needs improvement, but the Explore tab code is a bit weird, so it'll take time.
