### ISSUE TITLE
Own Profile in the Suggested Accounts to Follow section (Firefish)

### ISSUE THREAD

**Issue by ghost** [feditext/feditext#196]
**Describe the bug**
I see my own profile in the "Suggested Accounts to Follow" section.

**To Reproduce**
1. Go to 'Explore'
2. Click on 'Instance > Suggested Accounts to Follow'
3. See error

**Expected behavior**
Own profile not being there.

**Screenshots**
![my account, `@ewan@firefish.lgbt`, in that directory.](https://github.com/feditext/Feditext/assets/121812160/7818aa41-0897-4375-9a0e-4f386dafafd8)

**(please complete the following information):**
 - Device: [iPhone 8 Plus]
 - OS: [iOS 16.1]
 - App Version [1.7.2 (Build 70)]

**Additional context**
...

**Comment by VyrCossont** [comment]
@EwanCroft Firefish?

**Comment by ghost** [comment]
Yes!

**Comment by VyrCossont** [comment]
@EwanCroft Can you open a bug for this with Firefish, please? We can work around it it, but this should be fixed upstream.

**Comment by ghost** [comment]
@VyrCossont i'm not really able, i don't think.

I'll notify T1C on Fedi (I'll tag the project), as I don't have a Codeburg.

**Comment by ThatOneCalculator** [comment]
We're no longer on Codeberg, rather, our own Gitlab server. https://git.joinfirefish.org/firefish/firefish
