### ISSUE TITLE
BUG: iOS Share Sheet to FediText doesn't work

### ISSUE THREAD

**Issue by jeffsikes** [feditext/feditext#198]
**Describe the bug**
When using the share sheet from iOS apps to share a url, image or video to FediText, a "No account found" message appears after FediText is opened (there is an account logged in to FediText).

**To Reproduce**
1. Open Safari or Firefox on iOS (iPad or iPhone, tried both)
2. Go to any web page 
3. Choose the Share icon
4. Share to FediText
5. FediText does open, but a white pop up screen appears and says "No account found."

You can repeat steps with an image or video as well.

**Expected behavior**
Expectation is that a new post window would appear with the URL, image or video included. Not sure the exact behavior if you have more than one account in the app, however...

**Screenshots**
|<img src="https://github.com/feditext/feditext/assets/6627582/0734f49d-7569-47e6-a474-cb24b9e95a7d" width="200" />|<img src="https://github.com/feditext/feditext/assets/6627582/209f6dea-80f9-4061-bc31-cc604db59320" width="200"/>|

**(please complete the following information):**
 - Device: iPhone 14 Pro Max, iPad Air ??? newish
 - OS: iOS 16.6 on both
 - App Version 1.7.2 (64) on both

**Additional context**
Initially tried a screenshot, crop, etc. and then share. That didn't work, then tried opening Photos and sharing from there. Same pop up window stating "No account found." but I have 1 account on my iPhone (Firefish) and 2 accounts on the iPad (1 Mastodon, 1 Firefish) Further attempted a share from Safari and then Firefox, same behavior.

I do not think I have tried sharing a photo / link this way before in FediText.

**Comment by VyrCossont** [comment]
@jeffsikes I can't repro this on my own devices. Please update to build 70 by opening TestFlight, pulling to refresh if necessary, and tapping the Update button for Feditext. If the problem goes away, great; if it doesn't, the next step would be deleting the app and reinstalling fresh from TestFlight, in case there was some upgrade path from previous beta versions that left the app's extensions unable to read the core app's data.

It's not triggered solely by multiple accounts, because I'm logged into six on the phone I'm typing this on.

**Comment by jeffsikes** [comment]
Strange, TestFlight is showing FediText as "Previously Tested, Build Removed", version 1.7.2 (59). 

I have build 1.7.2 (64) installed on all three of my devices (Mac, iPad, iPhone).

But, I don't see FediText in my list of TestFlight apps to update or install (I pulled down to refresh, closed the app, even restarted the phone).

I'll give it a day or two and see if the dust settles. I've had this issue with other test builds but I hope it's not the same thing. It was a global issue with Apple's TestFlight app. Caused the devs a lot of headaches and had to re-send invites to a new entry on TestFlight.

**Comment by VyrCossont** [comment]
@jeffsikes DM https://fedi.software/@Feditext and I'll send you a new enrollment link. We briefly had a second beta group to work around some kind of provisioning problem on Apple's side, but it's since been switched off. It's possible you were in that group.

**Comment by jeffsikes** [comment]
Thank you. Yes, confirmed as working for images, videos and links with the new enrollment and updated version on all 3 devices. I did notice that 

So...nevermind. At least if someone comes along with the same behavior and searches the issue list, maybe it will stop them from submitting another new issue.
