### ISSUE TITLE
Welcome message still has "Metatext" in it

### ISSUE THREAD

**Issue by melgu** [feditext/feditext#202]
**Describe the bug**
The welcome message still mentions Metatext.

**To Reproduce**
1. Make sure you are logged out and the app is fully closed.
2. Open it.

**Expected behavior**
Welcome message with the new Feditext name.

**Screenshots**
![image](https://github.com/feditext/feditext/assets/9601403/59fe8108-9684-426c-8ee9-d276f803705c)

**(please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 17 Beta (21A5303d)
 - App Version 1.7.2 (70)

**Comment by VyrCossont** [comment]
We're not updating non-English localizations during this phase of the beta, so many strings still mention Metatext and new features will be missing non-English text and will appear as `localization-keys.that.look.like.this`. Please switch the app to English for now; we'll announce localization updates when they happen, but right now, we don't have the infrastructure in place yet. See #79.
