### ISSUE TITLE
Disable push notification UI on backends that don't have them

### ISSUE THREAD

**Issue by ghost** [feditext/feditext#206]
**Describe the bug**
Notifications are not being pushed. I can see them in-app and configure the settings, but there's nothing coming through to my Notification Centre.

**To Reproduce**
1. Have the app closed.
2. Get a notification. Any type is fine.
3. Check Notification Centre.

**Expected behavior**
The notification should be pushed to the Notification Centre.

**Screenshots**
...

**(please complete the following information):**
 - Device: [iPhone 8 Plus]
 - OS: [iOS 16.1]
 - App Version [1.7.2 (build 71)]

**Additional context**
...

**Comment by VyrCossont** [comment]
[Firefish doesn't actually support push notifications for Mastodon API clients](https://fedi.software/notes/9i9cz2gic123jzz8), so we should switch off push notification UI for it.

**Comment by VyrCossont** [comment]
GtS also lacks push support as of today.

**Comment by ghost** [comment]
Ah, damn. Hopefully it gets patched.

**Comment by VyrCossont** [comment]
Upstream bugs:
- https://git.joinfirefish.org/firefish/firefish/-/issues/10717
- https://iceshrimp.dev/iceshrimp/iceshrimp/issues/162

**Comment by KyoSakuyo** [comment]
> GtS also lacks push support as of today.

It seems like Tusky supports fetching GTS's notofications, how?

**Comment by VyrCossont** [comment]
GtS doesn't have push notifications either superseriousbusiness/gotosocial#1350 so it's either polling the notifications endpoint or maintaining an event streaming connection.

In either case, there are performance implications. We can look into that in the future, but I'm going to rename this bug to indicate the only changes planned for 1.7.

**Comment by VyrCossont** [comment]
Apparently push notification UI is *already* switched off on instances that can't register a push subscription, so this is done.
