### ISSUE TITLE
Media from trending posts don't open

### ISSUE THREAD

**Issue by yithian** [feditext/feditext#208]
**Describe the bug**
When tapping on media that are attached to trending posts, nothing happens

**To Reproduce**
1. Go to 'Explore'
2. Scroll down to 'Trending Posts'
3. Find a post with media attached to it (eg: an image)
4. Tap on the media to show the full version
5. Nothing happens

**Expected behavior**
The full media is displayed, just like in the 'Timelines' view

**Screenshots**
![Screenshot 2023-08-15 at 7 51 43 AM](https://github.com/feditext/feditext/assets/352965/df55801b-a128-4437-9638-43ad27c221d6)
Tapping on the image in the post from Radical Graffiti doesn't do anything but should display the full image

**(please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.6
 - App Version: 1.7.2 (71)

**Additional context**

**Comment by VyrCossont** [comment]
Thanks for the report! This is the same bug as #131.
