### ISSUE TITLE
Prebuilt IPAs in Releases for jailbroken devices

### ISSUE THREAD

**Issue by TheMemeSniper** [feditext/feditext#229]
**Is your feature request related to a problem? Please describe.**
Jailbroken users (such as myself) can install IPAs directly from the device without the use of TestFlight. Compiling is a time consuming process that requires Xcode, a macOS only app.

**Describe the solution you'd like**
Add the IPA to the latest release tag.

**Describe alternatives you've considered**
I don't know of any alternatives.

**Additional context**
Jailbreaks can allow the installation of apps without a signature from Apple

**Comment by VyrCossont** [comment]
Thanks for flagging this. It's not a high priority but we might look into it in the future. If you can provide a reliable way to test that the IPAs are actually installable by jailbreak users without requiring me to own a jailbroken device for testing, that'd help.

**Comment by TheMemeSniper** [comment]
sure thing!

**Comment by TheMemeSniper** [comment]
since this app doesn't seem to use any jailbreak only libraries (that would have to be installed by a package manager) it should install just fine, i'll build the app and make sure though

**Comment by TheMemeSniper** [comment]
my app is bugging out right now sorry if i deleted any previous replies

i can't build an IPA because xcode keeps complaining about me not having paid my apple tax for code signing (even though i don't want it)

do one of y'all still have one of those IPAs from TestFlight?

**Comment by miacate** [comment]
bump, just publishing the IPA files would be a good idea since things like sidestore/altstore and trollstore exist

**Comment by VyrCossont** [comment]
Yeah, I'm not really interested in supporting a different deployment configuration. Y'all can always build it yourselves.
