### ISSUE TITLE
Video preview incorrectly uses image from unrelated toot

### ISSUE THREAD

**Issue by sporklet** [feditext/feditext#234]
In a toot with embedded video, the preview image appears to have been recycled from the next-oldest toot-using-media in the timeline. Tapping to view the affected toot in-app shows a blank preview with link icon.

**To Reproduce**
Follow both @BBCRadio4@social.bbc and @kevinrothrock@infosec.exchange, then scroll through Home timeline

**Screenshots**
![IMG_3039](https://github.com/feditext/feditext/assets/3883042/bbb3c96c-d9e1-4967-8211-9ec842ec684f)

**(please complete the following information):**
 - Device: iPad Pro (2018)
 - OS: iPadOS 17 PB3
 - App Version: 1.7.2 (73)

**Comment by VyrCossont** [comment]
I think this is the same underlying bug as #107 and possibly #218. We'll track it as part of #107.
