### ISSUE TITLE
Add separate default privacy for replies 

### ISSUE THREAD

**Issue by rrgeorge** [feditext/feditext#236]
**Is your feature request related to a problem? Please describe.**
I like to keep my default for new posts set to Public, but usually prefer to reply as Unlisted. It would be nice to be able to set this as an option. 

**Describe the solution you'd like**
I would like to be able to set a different posting default for replies.

**Describe alternatives you've considered**
remembering to change my post privacy when replying

**Additional context**
n/a

**Comment by VyrCossont** [comment]
Tracked under #161.

**Comment by rrgeorge** [comment]
> Tracked under #161.

I swear I searched for this a million different ways 🤦‍♂️
