### ISSUE TITLE
Scrolling breaks images

### ISSUE THREAD

**Issue by cogrrl** [feditext/feditext#252]
**Describe the bug**

When scrolling on home timeline, inline images intermittently draw incorrectly with stripes/smears instead of part of the image. Clicking on the image displays it correctly. So does scrolling more slowly beyond and back across post with image. It doesn't require really rapid scrolling to induce behavior. Closing/restarting app doesn't help. Rebooting iphone doesn't help. Not affected by wifi network speed. May occur more to higher contrast images

![IMG_5189](https://github.com/feditext/feditext/assets/142918256/5b3f163f-cb15-4b07-8122-0d73b0a6e784)

![IMG_5188](https://github.com/feditext/feditext/assets/142918256/0278bbe8-2928-4edc-8909-6c32ff4d8b52)
 

**To Reproduce**
1. Go to Home timeline 
3. Scroll quickly down posts with images

**Expected behavior**

Inline images should display correctly all the time

**Screenshots**

Correct and incorrect screengrabs attached

**(please complete the following information):**
 - Device:  iPhone 11 Pro
 - OS: iOS 16.6.1
 - App Version 1.7.2

**Additional context**

**Comment by bdube** [comment]
Thank you. I'll combine this one with issue #185.
