### ISSUE TITLE
404 when trying to reply to deleted post

### ISSUE THREAD

**Issue by cogrrl** [feditext/feditext#271]
**Describe the bug**
A clear and concise description of what the bug is. While looking at Notifications, I attempted to reply in a Public thread to someone who addressed a reply to me. 

I get a 404 error that is not informative. I can click on Reply and type into text box but not Post it. Clicking Post produces a cryptic error message. It may be this post has been deleted by the author but the error message doesn't indicate that. 

Cancel is the only way to go back to scrolling the Notification list or Home timeline

This doe not appear to be the same as another 404 bug already posted

**To Reproduce**
1. Go to my Notification from @zeruela at mastodon.world. It is dated 10/8/23 9:46 pm. Click on reply icon
2. Enter text to reply 
3. Click on Post
4. See error shown in screenshot below

**Expected behavior**
I may be seeing and attempting to reply to a deleted post. A deleted post should not show up in Notifications after refreshing the list/restarting the app or should display an error message stating that post has been deleted 

**Screenshots**
![image](https://github.com/feditext/feditext/assets/142918256/7be77fae-5698-4704-bda9-2f3426e3bb85)

**(please complete the following information):**
 - Device:  iPhone 11Pro
 - OS: iOS 16.6.1
 - App Version 1.7.2 (76)

**Additional context**
Add any other context about the problem here
JSON from error

```json
{
  "alertLocation" : {
    "file" : "ViewModels/ComposeStatusViewModel.swift",
    "function" : "post(viewModel:inReplyToId:)",
    "line" : 303
  },
  "app" : {
    "build" : "76",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "method" : "POST",
    "reason" : "invalidStatusCode",
    "requestLocation" : {
      "file" : "ServiceLayer/IdentityService.swift",
      "function" : "post(statusComponents:)",
      "line" : 370
    },
    "statusCode" : 404,
    "url" : "https://vmst.io/api/v1/statuses"
  },
  "message" : "POST https://vmst.io/api/v1/statuses\n\nHTTP Error: 404",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.6.1"
  },
  "title" : "HTTPError",
  "type" : "HTTPError"
}
```

**Comment by VyrCossont** [comment]
Thanks for the report. We definitely need a better error message for this case.

**Comment by VyrCossont** [comment]
Related to #100.

**Comment by VyrCossont** [comment]
Will handle this as part of #100.
