### ISSUE TITLE
Hashtag umlaut substitution results in wrong alternative spelling

### ISSUE THREAD

**Issue by elosha** [feditext/feditext#273]
**Describe the bug**
I don't know if umlaut substitution is a feature of Mastodon or this app, please enlighten me ;)

When a hashtag contains a German umlaut, like "#servicetröt", the umlaut ö is rewritten to "o", which results in wrong spelling. In German, the only correct alternative spelling is "oe". Same for other umlauts. Tröt is the German term for toot, so it happens often.

For the hashtag "#spaß" (fun), the ß is not being rewritten at all.

**To Reproduce**
1. Switch app or system to German
2. Start a post
3. Add a hashtag that contains an umlaut, for example "#tröt"
4. You get the erroneous suggestion "#trot" first
5. Force entry of "#tröt"
6. The text will be posted with two hashtags, "#tröt" (original, correct) and "#trot" (rewritten, wrong)

**Expected behavior**
If the client app is responsible for letter substitution:

Keep the method to post with original and rewritten hashtag, it's a good idea. But if the locale is set to German (doesn't matter if Germany, Austria, Switzerland) or Scandinavian languages, the rewrite needs to use the proper character substitution table:

- ä = ae
- ö = oe
- ü = ue
- Ä = Ae
- Ö = Oe
- Ü = Ue
- ß = ss (Caution: That's an Eszet, not Beta ;) )

*Limit to German and Scandinavian locales is necessary, because non-germanic languages use the Trema (double dot) for other reasons, which need to keep the existing substitution!*

Some scandinavian languages use similar substitutions:

- ø = oe
- Ø = Oe
- æ = ae
- Æ = Ae

French:

- œ = oe
- Œ = OE

*Scandiniavian/French letters should be global substitutions because they have no different alternative spellings elsewhere!*

**(please complete the following information):**
 - Device: iPhone SE 2 (2020)
 - OS: iOS 16.7.1
 - App Version: 1.7.2 (Testflight latest)

**Additional context**
- System language: German
- System keyboard: German
- Instance: Mastodon 4.2.1

**Comment by VyrCossont** [comment]
Unfortunately, this diacritic mangling is a Mastodon problem, and intentional behavior. You'd think Eugen would have gotten this right since he lives in Germany. Other servers may have different behavior.

**Comment by elosha** [comment]
Thanks, I'll check out what they say :)
