### ISSUE TITLE
Status already taken error 

### ISSUE THREAD

**Issue by cogrrl** [feditext/feditext#276]
**Describe the bug**

App crashed with "Status has already been taken" error after clicking on Like icon twice

**To Reproduce**
1. Go to any post
2. Click on Like icon to highlight
3. Click on image in post
4. Close image with X icon
5. Click on Like icon again 
6. See error

**Expected behavior**

App should not crash when clicking on Like icon whether it has been clicked on or not. Should be able to toggle like on and off

**Screenshots**

**(please complete the following information):**

 - Device: iPhone 11pro
 - OS: iOS 16.6.1
 - App Version 1.7.2 (76)

**Additional context**

JSON error message
```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "events",
    "line" : 356
  },
  "app" : {
    "build" : "76",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "apiCapabilities" : {
      "features" : [

      ],
      "flavor" : "mastodon",
      "nodeinfoSoftware" : {
        "name" : "mastodon",
        "version" : "4.3.0-alpha.0+io"
      },
      "version" : "4.3.0-alpha.0+io"
    },
    "apiError" : {
      "error" : "Validation failed: Status has already been taken"
    },
    "method" : "POST",
    "requestLocation" : {
      "file" : "ServiceLayer/StatusService.swift",
      "function" : "toggleFavorited(identityId:)",
      "line" : 68
    },
    "statusCode" : 422,
    "url" : "https://vmst.io/api/v1/statuses/111238365413732495/favourite"
  },
  "message" : "POST https://vmst.io/api/v1/statuses/111238365413732495/favourite\n\nValidation failed: Status has already been taken",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "16.6.1"
  },
  "title" : "AnnotatedAPIError",
  "type" : "AnnotatedAPIError"
}
```

**Comment by VyrCossont** [comment]
Looks like vmst.io is running an alpha build. I wonder if this is new behavior in Mastodon 4.3, or possibly a server bug. Have you seen this on any other instances?

**Comment by cogrrl** [comment]
I didn't realize we're on an alpha. I don't know when beta will be released or when @***@***.*** plans to migrate usI haven't tried other instances but I can if you wishthanks LisaOn Oct 16, 2023, at 3:29 PM, Vyr Cossont ***@***.***> wrote:﻿
Looks like vmst.io is running an alpha build. I wonder if this is new behavior in Mastodon 4.3, or possibly a server bug. Have you seen this on any other instances?

**Comment by VyrCossont** [comment]
Can't repro this. If it was a server bug, it's been fixed.
