### ISSUE TITLE
Doesn't fetch older posts after first sign-in

### ISSUE THREAD

**Issue by meljoann** [feditext/feditext#290]
**Describe the bug**
I've just signed in on my Mastodon and Gotosocial accounts, on iOS. Both displayed maybe 20 posts, and when I scrolled to the bottom it didn't fetch older posts. 

**To Reproduce**
1. Sign in for the first time 
2. Scroll down the the bottom of your feed
3. Older posts won't load
4. No spinner displayed, but a spinner appeared when I reached the bottom for the second time. However, no new posts loaded.

**Expected behavior**
I've switched Fedi clients recently (Mastotoot -> Tusker), and I could scroll down indefinitely. Maybe it's not healthy ;) but I expected Feditext to have this behaviour?

 - Device: iPhone 11
 - OS: iOS 16.6.1
 - App Version 1.7.2

**Comment by VyrCossont** [comment]
@meljoann This is a recently reported bug with today's build 77 aka 1.7.2 (77). To fix this, please open TestFlight, tap the Feditext row (but not the Update or Open button in that row), tap Previous Builds, and install 1.7.2 (76). Please let me know if that fixes your problem.

**Comment by meljoann** [comment]
Yes, that fixes it! Thanks! Sorry about the doubling-up, did a search but didn't see a similar issue 👍

**Comment by VyrCossont** [comment]
No worries! The issue wasn't reported on GitHub and duplicates happen anyway.

**Comment by joan7770** [comment]
Yeah have same issue on the new build, will keep older build on my phone.

**Comment by meljoann** [comment]
Hm, it's with having loaded more posts than I could in the original issue, but I just want to report:

I'm getting a similar "can't scroll down for more posts" issue in other clients.

I can't remember this happening before. Is there something new with a Mastodon update? Clients, iOS: Tusker & Ice Cubes
