### ISSUE TITLE
Deleting a cached copy of a deleted post triggers an AnnotatedAPIError

### ISSUE THREAD

**Issue by Seirdy** [feditext/feditext#293]
**Describe the bug**
If FediText fetches one of my posts which I subsequently delete on another client, attempting to delete it triggers an error. The post remains present even after refreshing the timeline, and only disappears when quitting and re-opening the app.

**To Reproduce**
1. Fetch one of your posts. Have it open or have it visible on a timeline/thread.
2. Keep FediText open and open the post on another client.
3. On the other client, delete the post.
4. Go back to FediText and attempt to delete the post.
5. See error

**Expected behavior**
The post disappears, or the app alerts me that the post no longer exists.

**Logs**

```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "events",
    "line" : 356
  },
  "app" : {
    "build" : "77",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "apiCapabilities" : {
      "features" : [

      ],
      "flavor" : "akkoma",
      "version" : "3.10.4-0-g0af8e93"
    },
    "apiError" : {
      "error" : "Record not found"
    },
    "method" : "DELETE",
    "requestLocation" : {
      "file" : "ServiceLayer/StatusService.swift",
      "function" : "delete()",
      "line" : 102
    },
    "statusCode" : 404,
    "url" : "https://pleroma.envs.net/api/v1/statuses/AbXqBKfKHpuOUQI6VM"
  },
  "message" : "DELETE https://pleroma.envs.net/api/v1/statuses/AbXqBKfKHpuOUQI6VM\n\nRecord not found",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.1"
  },
  "title" : "AnnotatedAPIError",
  "type" : "AnnotatedAPIError"
}
```

**Comment by VyrCossont** [comment]
Thanks for the report! This is pretty much the same issue as the remaining half of #100.
