### ISSUE TITLE
Only 15 posts loading

### ISSUE THREAD

**Issue by cogrrl** [feditext/feditext#301]
**Describe the bug**
Since early yesterday only 10-20 posts show up in Home, Local, Federation and Notifications tabs. Pulling down to refresh does nothing.

Appears to be related to number of posts loaded not age of posts. At this moment I can only see posts up to 6 minutes old. In the middle of the night I saw posts up to 2 hours old. But never more than 20.

In multiple other iOS apps, timeline is normal with scrolling through hours/days of posts and notifications and refreshing works normally. 

I have closed app and restarted iphone. I have disconnected and reconnected to wifi and tried different networks without improvement.

**To Reproduce**
1. Go to Home
2. Scroll down as far as you can. Speed of scrolling does not matter 
3. 
4. See error (further posts do not load)

**Expected behavior**
Scrolling should show older posts and notifications 

**Screenshots**
NA

**(please complete the following information):**
 - Device: iPhone 11Pro
 - OS:  iOS 16.6.1
 - App Version  1.7.2 (77)

**Additional context**
Old Metatext app continues to work fine

**Comment by SammyCola** [comment]
Appears in 1.7.2 (77), reverting to 1.7.2 (76) restores older posts loading.

**Comment by VyrCossont** [comment]
@cogrrl as @UltimateNova1203 says, this is a bug in build 77 (see #290). Reverting to build 76 fixes it, and I'll release a new build with a permanent fix sometime today.

**Comment by cogrrl** [comment]
Thanks much. Sorry I did not see it had been reported previously.LisaOn Nov 7, 2023, at 5:35 PM, Vyr Cossont ***@***.***> wrote:﻿
@cogrrl as @UltimateNova1203 says, this is a bug in build 77 (see #290). Reverting to build 76 fixes it, and I'll release a new build with a permanent fix sometime today.
