### ISSUE TITLE
ul bullets are not rendered consistently

### ISSUE THREAD

**Issue by mirabilos** [feditext/feditext#309]
Another very minor one, maybe for hacktoberfest or onboarding a new contributor or something?

**Describe the bug**
In some toots with an `ul` inside (e.g. from a Markdown `- foo\n- bar\n` list), the bullets are not rendered in a consistent size.

**To Reproduce**
1. Go to `web+ap://toot.mirbsd.org/@mirabilos/statuses/01HF2VDBF0NK856P11VC2R9WVF`
2. See this

**Expected behavior**
The bullets are rendered all in the same size

**Screenshots**
![yes](https://github.com/feditext/feditext/assets/861078/651dab67-f089-48e9-9597-cb7749250849)

**(please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.8 (latest)
 - App Version: 1.7.2 (78)

**Comment by VyrCossont** [comment]
@mirabilos Thanks for the report. I think this behavior is another example of #308, in which we're applying styles to list bullets that they should be excluded from, and will have the same fix.

**Comment by VyrCossont** [comment]
Confirmed related to #308.
