### ISSUE TITLE
GIF pics cant be played repeatedly, and if I tap a GIF image for many times the app will crash

### ISSUE THREAD

**Issue by 9264326** [feditext/feditext#327]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**(please complete the following information):**
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 14.4.1]
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by VyrCossont** [comment]
Please fill out the repro information completely. An example post that triggers the crash would be helpful, or a video of the crash.

**Comment by VyrCossont** [comment]
Not enough to repro.
