### ISSUE TITLE
Can't open profile editor web page for GotoSocial

### ISSUE THREAD

**Issue by VyrCossont** [feditext/feditext#33]
See superseriousbusiness/gotosocial#1100.

**Comment by mirabilos** [comment]
It works if you use “Edit Profile”

**Comment by daenney** [comment]
This might've all gotten fixed by both changes we've done on the GtS side and improvements in Feditext. Is there a Testflight or something I could load up on my phone? I have an iPhone but no macOS device so I can't build Feditext myself unfortunately.

**Comment by VyrCossont** [comment]
@daenney DM me at @vyr@demon.social or @vyr@princess.industries and I'll send you a TestFlight link. It does look like it's working, though, or at least the links open to actual pages that can be logged into on my own GtS instance.

**Comment by daenney** [comment]
I've tried the DM, but I'm now wondering if GtS does DMs because my clients are distinctly failing at loading the DM view :sweat_smile:. If that doesn't arrive, mind if I reach out over Matrix?

**Comment by daenney** [comment]
Ah, well, seems it worked. Can confirm that at least with GtS 0.10-rc1 and current version of Feditext both the "Edit Profile" and "Account Settings" open up a webview, I can log in and get to my profile etc. So somewhere along the way things got fixed!

**Comment by VyrCossont** [comment]
Fantastic. I'll close this out and sometime in the future I'll get around to building a native UI profile editor.

**Comment by mirabilos** [comment]
Daenney dixit:

>I've tried the DM, but I'm now wondering if GtS does DMs because my
>clients are distinctly failing at loading the DM view :sweat_smile:. If

DMs are just posts with Visibility=Direct. GtS does not (yet) implement
the DM overview view, but it does support sending and receiving them
just fine.

bye,
//mirabilos
-- 
> Wish I had pine to hand :-( I'll give lynx a try, thanks.

Michael Schmitz on nntp://news.gmane.org/gmane.linux.debian.ports.68k
a.k.a. {news.gmane.org/nntp}#news.gmane.linux.debian.ports.68k in pine
