### ISSUE TITLE
Allow hiding of fave and boost buttons

### ISSUE THREAD

**Issue by KitRedgrave** [feditext/feditext#330]
**Is your feature request related to a problem? Please describe.**
I'm finding that having the favorite and boost/repost buttons in front of me encourages me to use fedi in a shallow way that I don't like, and I'd like to have a way to precommit to interact much more personally.

**Describe the solution you'd like**
I would like for there to be an option in the settings menu each for hiding the fave and boost buttons entirely, and for the buttons to be gone from posts when it's set.

**Describe alternatives you've considered**
I've considered just using the existing double-tap to fave or boost, and that addresses the underlying concern somewhat. I've also considered doing this on a future serverside basis for myself, but that's a much heavier hand than this.

**Comment by VyrCossont** [comment]
This is a very niche feature and I can't promise I'll get to it unless there's substantial user interest.
