### ISSUE TITLE
Replies are not appended at the bottom

### ISSUE THREAD

**Issue by mirabilos** [feditext/feditext#340]
**Describe the bug**
When I zoom into a post to read the replies, FediText loads the first couple of them, then I scroll down, and the newly-loaded ones are somehow “up” of where I already was and the ones I was just reading have jumped down to the bottom, so I have to scroll either to the top to restart reading, or to the bottom to continue where I was then go to the top anyway.

**To Reproduce**
1. Zoom into a post that has many replies
2. Begin reading the replies, slowly scrolling down
3. At some point, things jump

**Expected behavior**
When new content is loaded in replies, it is appended at the bottom so I don’t have go go back up nor do I get posts I already saw.

**(please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.8 (latest)
 - App Version: 1.7.2 (80)

**Additional context**
Part of this may be an [instance](https://github.com/superseriousbusiness/gotosocial/issues/2479#issuecomment-1879377667) issue, but “clients can (and do) still jiggle replies around”, so let’s see if FediText can improve here.

**Comment by VyrCossont** [comment]
This is a GtS issue.

**Comment by mirabilos** [comment]
ok, thanks for confirming!
