### ISSUE TITLE
Allow setting lists as default/easily accessible timeline

### ISSUE THREAD

**Issue by ShadowJonathan** [feditext/feditext#349]
Currently, when using Toot!, i love that i'm able to set a list as my default home timeline, I'm using this to scope to a subset of mutuals to constantly scroll through their latest antics, while having the home feed / other lists on hand to look through.

This allows me to curate my experience much better than just a home feed, which is a firehose of everyone and everything, which can become very overwhelming quickly.

Could it be possible to set or "pin" a list to be accessible in the timeline feed selector? And/or automatically open on app launch? This way, I could better curate my feed while casually browsing. Currently it takes a few taps to get specifically into lists, steps that I know I won't default to, thus this request.

**Comment by VyrCossont** [comment]
Dupe of #27. Very much something I want too, since as you say, lists are inconvenient compared to many other clients.

**Comment by ShadowJonathan** [comment]
Thanks 💚
