### ISSUE TITLE
Test server and account for App Store reviewers

### ISSUE THREAD

**Issue by VyrCossont** [feditext/feditext#356]
> - Provide App Review with full access to your app. If your app includes account-based features, provide either an active demo account or fully-featured demo mode, plus any other hardware or resources that might be needed to review your app (e.g. login credentials or a sample QR code)
> - Enable backend services so that they’re live and accessible during review

— https://developer.apple.com/app-store/review/guidelines/#before-you-submit

A non-federating GtS testrig server might be ideal for this since they're trivial to reset.

**Comment by bdube** [comment]
I can make VMs available if that helps with this stuff.

**Comment by VyrCossont** [comment]
Set up. Instead of a non-federating GtS test rig, we'll be using an allow-list federating GtS server with a persistent database.
