### ISSUE TITLE
Feature Request: Link to original profile page on external instance

### ISSUE THREAD

**Issue by sgbx** [feditext/feditext#359]
On a feditext users profile overview, I cannot see posts and followers/ing, when I am not connected with the profile.

I would like to have an external link to the users profile page on the original server, e.g. in the little three dot menu on the top right hand side of a user profile.

Other apps (e.g. mastoot) have this feature included an I really appreciate it.

**Comment by VyrCossont** [comment]
The Feditext idiom for this kinda thing is to use the share sheet. In profiles specifically, use (…) menu → Share → Open in default browser (or Copy, or Open in Some Other Browser, etc.).
