### ISSUE TITLE
Sharkey notifications API uses wrong type for missing `Status.quote`

### ISSUE THREAD

**Issue by VyrCossont** [feditext/feditext#360]
**Describe the bug**
[Sharkey puts `false` where `null` or a `Status` should be.](https://activitypub.software/TransFem-org/Sharkey/-/issues/401)

**To Reproduce**
1. Log into a Sharkey instance
2. Try to use the Notifications tab
3. See error

**Expected behavior**
It works like Firefish or Iceshrimp or Akkoma or Treehouse or anything else that implements the `quote` extension to `Status` objects.

**(please complete the following information):**
 - Device: iPhone 15 Pro Max simulator
 - OS: iOS 17.0.1
 - App Version: 1.7.2 (86)

**Additional context**
```json
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:search:)",
    "line" : 370
  },
  "app" : {
    "build" : "3",
    "bundle" : "codes.catgirl.feditext",
    "version" : "1.7.2"
  },
  "error" : {
    "error" : {
      "typeMismatch" : {
        "context" : {
          "codingPath" : [
            "_JSONKey(stringValue: \"Index 0\", intValue: 0)",
            "CodingKeys(stringValue: \"status\", intValue: nil)",
            "CodingKeys(stringValue: \"quote\", intValue: nil)"
          ],
          "debugDescription" : "Expected to decode Dictionary<String, Any> but found bool instead."
        },
        "type" : "Swift.Dictionary<Swift.String, Any>"
      }
    },
    "method" : "GET",
    "requestLocation" : {
      "file" : "ServiceLayer/NotificationsService.swift",
      "function" : "request(maxId:minId:search:)",
      "line" : 69
    },
    "url" : "https://plasmatrap.com/api/v1/notifications"
  },
  "message" : "GET https://plasmatrap.com/api/v1/notifications\n\ntypeMismatch(type: \"Swift.Dictionary<Swift.String, Any>\", context: HTTP.AnnotatedDecodingError.EncodableContext(codingPath: [\"_JSONKey(stringValue: \\\"Index 0\\\", intValue: 0)\", \"CodingKeys(stringValue: \\\"status\\\", intValue: nil)\", \"CodingKeys(stringValue: \\\"quote\\\", intValue: nil)\"], debugDescription: \"Expected to decode Dictionary<String, Any> but found bool instead.\", underlyingError: nil))",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.0.1"
  },
  "title" : "AnnotatedDecodingError",
  "type" : "AnnotatedDecodingError"
}
```

**Comment by dtfleetwood** [comment]
Thank you for creating this for me, I'll be certain to create my own issues as I find them going forward!

**Comment by VyrCossont** [comment]
Looks like Sharkey will have a fix on their end soon.

**Comment by VyrCossont** [comment]
Expected to be fixed by https://activitypub.software/TransFem-org/Sharkey/-/merge_requests/407. I'll close this when the patch is merged, deployed to the servers I use for testing, and confirmed to actually fix the problem

**Comment by VyrCossont** [comment]
Still a problem on `transfem.social` and `plasmatrap.com`. It's possible they haven't cut a release with this patch yet, since I don't see a tag corresponding to what `transfem.social` is running.

**Comment by VyrCossont** [comment]
So due to a miscommunication and me failing to read the patch correctly, their [MR 407](https://activitypub.software/TransFem-org/Sharkey/-/merge_requests/407) actually *reintroduced* the already-fixed bug with a different cause. I should have followed up on [issue 401](https://activitypub.software/TransFem-org/Sharkey/-/issues/401) sooner. Talked with Marie and their [PR 480](https://activitypub.software/TransFem-org/Sharkey/-/merge_requests/480) should fix it for real this time, unblocking basic Feditext features for Sharkey users.

**Comment by VyrCossont** [comment]
Looks like Sharkey *finally* merged the fix last week. Seems to work okay on (flagship instance) transfem.social.
