### ISSUE TITLE
Some instances are blocked for opaque reasons

### ISSUE THREAD

**Issue by psandin** [feditext/feditext#362]
**Describe the bug**
Logging into some instances is disallowed without a clear reason being given.

**To Reproduce**
1. Go to 'add account’
2. Set the instance name to ‘eightpoint.app’
3. Click on ‘login'

**Expected behavior**
We’re allowed to log into whatever instances we have accounts on, or barring that there’s an explanation of the decision making process and where to appeal to.

**Additional context**
This seems like intended behavior there’s just no explanation of how or why it was intended, who made that determination, and on what basis.

**JSON**
```
{
  "alertLocation" : {
    "file" : "ViewModels/AddIdentityViewModel.swift",
    "function" : "addIdentity(kind:)",
    "line" : 111
  },
  "app" : {
    "build" : "87",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "message" : "In order to provide a safe experience to all users and comply with the App Store Review Guidelines, this instance is not supported.",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.2.1"
  },
  "title" : "AddIdentityError",
  "type" : "AddIdentityError"
}
```

**Comment by VyrCossont** [comment]
This is intended behavior. As in Metatext, some instances aren't supported. Feditext's blocklist is based on commonly used Fedi blocklists (mastodon.social, Garden Fence, Seirdy, Oliphant T1). Typical reasons for blocklisting include illegal material, spam, and/or harassment.
