### ISSUE TITLE
Siren does not render headlines

### ISSUE THREAD

**Issue by mirabilos** [feditext/feditext#371]
**Describe the bug**
Siren fails to render headlines (lines beginning with *n*\*`#`+space in Markdown).

This should be a blocker for #358 as Webkit does handle them.

**(please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.8.1 (latest)
 - App Version: 1.7.2 (89)

**Comment by VyrCossont** [comment]
Fails to render as in missing styles? Or fails to render as in they don't show up at all?

**Comment by mirabilos** [comment]
Vyr Cossont dixit:

>Fails to render as in missing styles?

It renders like a <span>, i.e. no formatting and not even
horizontal or vertical whitespace separating it from the
preceding paragraph.

**Comment by VyrCossont** [comment]
Thanks. Headers are rare but we should handle them correctly in Siren.

**Comment by VyrCossont** [comment]
Fixed by ddabd9fd629e5e48bef4bddd33d9d5197ba9061a.
