### ISSUE TITLE
AnnotatedDecodingError while loading timeline on modified Sharkey instance

### ISSUE THREAD

**Issue by ghostbloo** [feditext/feditext#376]
**Describe the bug**
An AnnotatedDecodingError appears while loading the home timeline for a Sharkey feed, specifically [lethallava.land](https://lethallava.land) which uses [a modified version of Sharkey](https://activitypub.software/esm/Sharkey/-/tree/lll-patch). No posts load and the error repeats upon tab change.

**To Reproduce**
1. Log in to Sharkey instance (lethallava.land)
2. Open timelines tab
3. Error appears, feed is blank.

**Expected behavior**
No error, posts appear as expected.

**Screenshots**
![canvas](https://github.com/feditext/feditext/assets/152131832/50e90ff4-9cf0-412b-bbd9-42f7c786fe1d)

**(please complete the following information):**
 - Device: iPhone SE (2022)
 - OS: iOS 17.3.1
 - App Version 1.7.2 (90)

**Additional context**
```
{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:)",
    "line" : 370
  },
  "app" : {
    "build" : "90",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "error" : {
      "typeMismatch" : {
        "context" : {
          "codingPath" : [
            "_JSONKey(stringValue: \"Index 0\", intValue: 0)",
            "CodingKeys(stringValue: \"quote\", intValue: nil)"
          ],
          "debugDescription" : "Expected to decode Dictionary<String, Any> but found bool instead."
        },
        "type" : "Swift.Dictionary<Swift.String, Any>"
      }
    },
    "method" : "GET",
    "requestLocation" : {
      "file" : "ServiceLayer/TimelineService.swift",
      "function" : "request(maxId:minId:)",
      "line" : 93
    },
    "url" : "https://lethallava.land/api/v1/timelines/home"
  },
  "message" : "GET https://lethallava.land/api/v1/timelines/home\n\ntypeMismatch(type: \"Swift.Dictionary<Swift.String, Any>\", context: HTTP.AnnotatedDecodingError.EncodableContext(codingPath: [\"_JSONKey(stringValue: \\\"Index 0\\\", intValue: 0)\", \"CodingKeys(stringValue: \\\"quote\\\", intValue: nil)\"], debugDescription: \"Expected to decode Dictionary<String, Any> but found bool instead.\", underlyingError: nil))",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.3.1"
  },
  "title" : "AnnotatedDecodingError",
  "type" : "AnnotatedDecodingError"
}
```

I haven't tested any other Misskey forks.

**Comment by VyrCossont** [comment]
Thanks for the report. This is the same issue as #360 and is a Sharkey bug that can be fixed by applying https://activitypub.software/TransFem-org/Sharkey/-/merge_requests/407. Please pass that on to the `lethallava.land` admins.
