### ISSUE TITLE
API / json Issue 

### ISSUE THREAD

**Issue by sgbx** [feditext/feditext#377]
I get the following error when trying to open the home timeline (not only Feditext affected, but started here)

{
  "alertLocation" : {
    "file" : "ViewModels/CollectionItemsViewModel.swift",
    "function" : "request(maxId:minId:)",
    "line" : 370
  },
  "app" : {
    "build" : "90",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "error" : {
      "dataCorrupted" : {
        "context" : {
          "codingPath" : [
            "_JSONKey(stringValue: \"Index 4\", intValue: 4)",
            "CodingKeys(stringValue: \"createdAt\", intValue: nil)"
          ],
          "debugDescription" : "Unable to parse ISO8601 date"
        }
      }
    },
    "method" : "GET",
    "requestLocation" : {
      "file" : "ServiceLayer/TimelineService.swift",
      "function" : "request(maxId:minId:)",
      "line" : 93
    },
    "url" : "https://my.url.com/api/v1/timelines/home"
  },
  "message" : "GET https://my.url.com/api/v1/timelines/home\n\ndataCorrupted(context: HTTP.AnnotatedDecodingError.EncodableContext(codingPath: [\"_JSONKey(stringValue: \\\"Index 4\\\", intValue: 4)\", \"CodingKeys(stringValue: \\\"createdAt\\\", intValue: nil)\"], debugDescription: \"Unable to parse ISO8601 date\", underlyingError: nil))",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.3.1"
  },
  "title" : "AnnotatedDecodingError",
  "type" : "AnnotatedDecodingError"
}

**Comment by pagenstedt** [comment]
I did some database maintenance tasks. Afterwards everything was fine. Sorry for confusion.

**Comment by sgbx** [comment]
I did some database maintenance tasks. Afterwards everything was fine. Sorry for confusion.
