### ISSUE TITLE
[Siren] Long post causes the timeline to blank

### ISSUE THREAD

**Issue by daenney** [feditext/feditext#382]
**Describe the bug**
When scrolling in my timeline today the GoToSocial 0.14 release post came into view and it seems to break things.

**To Reproduce**
1. Scroll the timeline
2. Come across a very long post
3. See error

**Expected behavior**
The post should render with a "show more" button and not break the timeline.

**Screenshots**

![siren-gts-feditext](https://github.com/feditext/feditext/assets/569574/e7257c5e-3fe7-4fd0-86f3-88fca777f453)

**(please complete the following information):**
 - Device: iPhone 12 mini
 - OS: iOS 17.4
 - App Version 1.7.2 (92)

**Additional context**

* This is with the Siren renderer, WebKit works fine
* I have large text enabled in the iOS accessibility settings

**Comment by VyrCossont** [comment]
Thanks for the report. No idea what's causing this yet, but we'll find out.

**Comment by VyrCossont** [comment]
The offending post:
https://gts.superseriousbusiness.org/@gotosocial/statuses/01HR9JYMBQ6HFSBZ094TCNC6XS

I could only repro on GtS, not Glitch, so whatever's causing the layout instability may be an HTML element that's stripped by Glitch but not GtS, and that narrows it down a bit.

**Comment by VyrCossont** [comment]
I've hit the bug twice more. Think it's related to the `<hr>` element, which was recently added to Siren and is stripped by Glitch but not GtS.

**Comment by daenney** [comment]
Ah yeah, GtS keeps `<hr>` because we use that for when the server attaches a notice to a status too (like when an attachment failed to fetch) if I remember right. The horizontal rule seems harmless in general so I'm surprised it's getting stripped.

**Comment by VyrCossont** [comment]
Think this is because the `hr` text decoration is being drawn outside the bounds of a folded post, since the draw code for those decorations is currently unaware of a post's folded status. Turning on clipping to bounds might fix this; if not, we can avoid drawing decorations if a post is folded.

This is the last dealbreaker Siren bug.

**Comment by VyrCossont** [comment]
Fixed in 816972d by turning on `masksToBounds` for the `CALayer` containing text decorations.
