### ISSUE TITLE
Colorize icons preference labels are weird

### ISSUE THREAD

**Issue by searchtools-avi** [feditext/feditext#386]
Preferences / Colorize visibility icon labels should be something that is not the letters **O, f, n**

![IMG_0381](https://github.com/feditext/feditext/assets/3218331/25090ad8-0d0b-4c08-86bb-cf10db1f46b4)

 - Device: iPhone15
 - OS: 17.4
 - App Version 1.7.2

**Comment by VyrCossont** [comment]
Thanks for the report. This is the same issue as #176.
