### ISSUE TITLE
Unable to respond to certain users

### ISSUE THREAD

**Issue by cogrrl** [feditext/feditext#398]
**Describe the bug**
Update: Problem not limited to  Feditext -same error using Tusker app too. So close this issue as you wish. I won't expect a solution. Sorry for opening it prematurely.

Yesterday I was unable to respond to a post in my notifications. I got a 404 error each time I tried. Today I got 404 error when trying to respond to a notification from @notroot@notroot.online. My attempted responses are text only, no special characters or images. Have power cycled phone and error persists.

**To Reproduce**
1. Go to my account using Feditext 
2. Click on Notifications tab/All
3. Scroll down to 4/8/24 response from  @notroot@notroot.online or to 4/7/24 response from @celadonCamellia@sakurajima.social
4. Click on reply icon. Enter text. Hit Post
5. See error (screenshot and json below)

**Expected behavior**
Should be able to respond to any user on any server that can see and respond to my posts. Vmst.io admin confirms problem is not server related

**Screenshots**
![image](https://github.com/feditext/feditext/assets/142918256/4919a3a3-4875-49ea-b37c-5abcca40791e)

**(please complete the following information):**
 - Device: iPhone 11Pro
 - OS: iOS 17.3.1
 - App Version 1.7.2 (103)

**Additional context**
Same problem has happened sporadically in the past.

```json
{
  "alertLocation" : {
    "file" : "ViewModels/ComposeStatusViewModel.swift",
    "function" : "post(viewModel:inReplyToId:)",
    "line" : 319
  },
  "app" : {
    "build" : "103",
    "bundle" : "com.gotgoat.metatext",
    "version" : "1.7.2"
  },
  "error" : {
    "method" : "POST",
    "reason" : "invalidStatusCode",
    "requestLocation" : {
      "file" : "ServiceLayer/IdentityService.swift",
      "function" : "post(statusComponents:)",
      "line" : 371
    },
    "statusCode" : 404,
    "url" : "https://vmst.io/api/v1/statuses"
  },
  "message" : "POST https://vmst.io/api/v1/statuses\n\nHTTP Error: 404",
  "system" : {
    "idiom" : "phone",
    "model" : "iPhone",
    "name" : "iOS",
    "version" : "17.3.1"
  },
  "title" : "HTTPError",
  "type" : "HTTPError"
}
```

**Comment by VyrCossont** [comment]
Yeah, not sure what's going on there, but if it happens in Tusker as well, it's very unlikely to be Feditext-specific.
