### ISSUE TITLE
Tapping on link to toot, loads toot then returns to original post

### ISSUE THREAD

**Issue by rrgeorge** [feditext/feditext#405]
**Describe the bug**
When a toot contains a link to another toot, tapping on it loads it, then returns to the original post. Tapping on it again loads it properly

**To Reproduce**
1. Find a post in your timeline with a link to another post or mention
2. Tap on the link
3. Observe the behavior

**Expected behavior**
For the post/profile to load and stay there

**Screenshots**
*Will update with video next time I encounter it.*

**(please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 17.4.1
 - App Version 1.7.2(106)

**Additional context**
I *think* it's probably because the app doesn't contain a cache of the linked post, so it's needing to fetch it. Which is why it doesn't do it when you tap the link a second time.

**Comment by VyrCossont** [comment]
I've seen it too and concur that it's probably nav cache related.

**Comment by VyrCossont** [comment]
This should be fixed in build 109.
