### ISSUE TITLE
unexpected icon change overnight suddenly

### ISSUE THREAD

**Issue by ae-s** [feditext/feditext#411]
**Describe the bug**
Feditext has rapid-onset icon dysphoria

**To Reproduce**
1. Have "rainbow paint" selected
2. Wait?
3. Observe "trans paint" is in effect

**Expected behavior**
I didnt expect the icon to change overnight.

**Screenshots**
![image](https://github.com/feditext/feditext/assets/172920/98a095c5-f233-4ee1-be3d-036eca57582c)
![image](https://github.com/feditext/feditext/assets/172920/ba426ae0-5da1-4e5a-838e-ce4ea3e2e6ce)

**(please complete the following information):**
 - Device: iPhone 13 mini
 - OS: iOS 17.4.1
 - App Version 1.7.2 (109)

**Additional context**

**Comment by VyrCossont** [comment]
Repeating for the issue tracker: The default icon change was intentional (it's the variant we use for the project account on Mastodon, and the one we'll be using in the App Store release) but it looks like there's a bug in the icon switcher as well. Thanks for reporting it.

**Comment by jmd-aKBar** [comment]
Adding a comment to note similar issue is observed on the iPhone 15 Pro as well. Switching to the "Rainbow Paint" icon brings up (and applies) the "Trans Paint" icon.

**Comment by VyrCossont** [comment]
Should be fixed in today's build 110. There's a new app icon setting called "Default", which is the same as the "Trans Paint" icon today, but will change if we change the default app icon later. If you explicitly set the app icon to something other than "Default", it will stay there.
