### ISSUE TITLE
Follow request menu does not appear (Iceshrimp)

### ISSUE THREAD

**Issue by arimelody** [feditext/feditext#421]
**Describe the bug**
while logged into an iceshrimp instance (possibly firefish too; i have no means to test this atm), the follow request option does not appear in the profile sheet.

**To Reproduce**
1. log in with an iceshrimp account.
2. open the profile sheet.

**Expected behavior**
the option to view follow requests should appear underneath "bookmarks" in the profile sheet on iceshrimp instances.

**Screenshots**
![image](https://github.com/feditext/feditext/assets/38161443/8bca5466-3040-4cdc-98eb-5a60fe5d9e93)

**(please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 17.5.1
 - App Version: 1.7.2

**Comment by VyrCossont** [comment]
The follow request menu item only shows up if you actually have follow requests. Just to confirm, you can see follow requests in other apps such as the Iceshrimp web frontend?

It's possible Iceshrimp didn't correctly implement the API that returns the follow request count.

**Comment by arimelody** [comment]
i can indeed see follow requests in iceshrimp's frontend, and the ice cubes app!
i can double-check the iceshrimp codebase to see what their API endpoint returns- what exactly does feditext try to hit?

**Comment by VyrCossont** [comment]
It's using the [`.source.follow_requests_count`](https://docs.joinmastodon.org/entities/Account/#follow_requests_count) property returned from the [`verify_credentials`](https://docs.joinmastodon.org/methods/accounts/#verify_credentials) endpoint. If your instance is returning the wrong type (int as a string, maybe?) compared to other implementations like Mastodon proper or GotoSocial, it could cause this.

**Comment by arimelody** [comment]
interesting... it appears iceshrimp doesn't return this property at all!

the only way i can find to retrieve this data is by checking `/api/i`'s `hasPendingReceivedFollowRequest` property (boolean), and then checking through every item of `/api/i/notifications`' looking for `type = "receiveFollowRequest"` items. (i do not like this either)

i'll flag this up with the iceshrimp devs and see if this can be introduced into their masto API endpoint. thanks!

**Comment by arimelody** [comment]
hmm... i've applied a patch to my own server that now sends `source.follow_request_count` on `/api/v1/accounts/verify_credentials`, however the option still does not appear. are there any other requests that need to be fulfilled before the option appears?

**Comment by VyrCossont** [comment]
Please attach an example of the JSON returned from that endpoint. If that doesn't look like the problem, I'll ask for an account on that patched server so I can do my own debugging.

**Comment by VyrCossont** [comment]
Oh. I may have misspelled it: it's `follow_requests_count` with `requests` plural.

**Comment by arimelody** [comment]
> Oh. I may have misspelled it: it's `follow_requests_count` with `requests` plural.

oh dear, that's an embarassing typo on my part LOL
i've amended my fork to use the plural version- can confirm the button now appears! i'll push this to my PR and hopefully get it merged to iceshrimp :)

**Comment by VyrCossont** [comment]
Thanks so much! When you open a PR, please link it back here so I can close this when it's eventually merged.

**Comment by arimelody** [comment]
happy to report it's already merged! https://iceshrimp.dev/iceshrimp/iceshrimp/pulls/557
