### ISSUE TITLE
Post text in notification truncated at first ampersand (&)

### ISSUE THREAD

**Issue by ae-s** [feditext/feditext#431]
**Describe the bug**
When I receive a system notification regarding a post whose text contains the ampersand (`&`) character, the text is truncated right up to the point of the ampersand.

**Screenshots**

![5CA48FA2-3DD5-4331-A295-E3FAF66D9178_1_201_a](https://github.com/user-attachments/assets/76976eb7-1447-4c0c-9538-6e6fc2f20720)

![019CC5F6-EFDC-40B9-BCED-A1BA9BE99721_1_201_a](https://github.com/user-attachments/assets/913f7549-cbaa-4afb-87cf-113da3c0e23c)

**(please complete the following information):**
 - Device: Iphone 13 mini
 - OS: IOS 17.5.1
 - App Version 1.7.2 (115)

**Comment by VyrCossont** [comment]
Thanks for the report. This sounds like #286.
