### ISSUE TITLE
[Community] Hi! I'd like to join the community to keep developing metatext

### ISSUE THREAD

**Issue by horaceyoung** [feditext/feditext#74]
As the title suggests, let me know if there's any communication channel that I can join and contribute to :)

**Comment by bdube** [comment]
Hello and thanks for your interest in the project. We have a fediverse chat going and I will respond there.

**Comment by horaceyoung** [comment]
Hi I'd like to ask how can I join TestFlight?

**Comment by bdube** [comment]
Hi, this is our [TestFlight](https://testflight.apple.com/join/A1j3P7wd). Thanks.

**Comment by bdube** [comment]
And discussions have been enabled for the repository.
