### ISSUE TITLE
New User Notifications unclear 

### ISSUE THREAD

**Issue by rrgeorge** [feditext/feditext#75]
**Describe the bug**
New user notifications are unclear. The show as:
> Notification from NewUser
> NewUser
> `@newuser`

**To Reproduce**
1. Create a new user account on your server
2. Go to the notifications tab
3. Go to Admin section
4. See notification

**Expected behavior**
The notification text should match the webui and say “NewUser has signed up” 

**Screenshots**

**(please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5
 - App Version 1.7.2 (35)

**Additional context**

**Comment by VyrCossont** [comment]
Looks like I missed an underscore here: https://github.com/bdube/metatext/blob/app-store-testflight/Mastodon/Sources/Mastodon/Entities/MastodonNotification.swift#L49

`admin.signup` should be `admin.sign_up`: https://docs.joinmastodon.org/entities/Notification/#type

**Comment by VyrCossont** [comment]
![image](https://github.com/bdube/metatext/assets/26195552/d9c1b5d8-4b31-4a7b-80c0-45315bb7e261)

Fixed. Should look like this once the build hits your device. Tapping the notification will navigate to the new user's profile.
