### ISSUE TITLE
Bio Links do not open

### ISSUE THREAD

**Issue by rrgeorge** [feditext/feditext#84]
**Describe the bug**
Tapping on a link in a profiles bio does not open it. 
 
**To Reproduce**
1. Go to a profile
2. Click on a link
3. Observe nothing happening 

**Expected behavior**
For the link to open in a browser

**Screenshots**

https://github.com/bdube/metatext/assets/8526392/c8933a3a-a065-4c2c-9af6-94d677fa5272

**(please complete the following information):**
 - Device: iPhone 12 Peo
 - OS: ios 16.5
 - App Version 1.7.2 (42)

**Additional context**

**Comment by horaceyoung** [comment]
The links work on appstore metatext. It also omits the 'https://' of a URL.

**Comment by horaceyoung** [comment]
Addressed in PR #86
