### ISSUE TITLE
Clicking on a clickable username doesn't direct to the user's profile view

### ISSUE THREAD

**Issue by horaceyoung** [feditext/feditext#97]
**Describe the bug**
As the title suggests

**To Reproduce**
1. Go to any post that has a clickable username.
2. Click on it.
3. It doesn't direct you to the profile page of the user

**Expected behavior**
The clickable username should direct you to the profile page of the user

**(please complete the following information):**
 - App Version 1.7.2 [48]

**Comment by VyrCossont** [comment]
Should be fixed in the next build.

**Comment by mirabilos** [comment]
Same here, e.g. the two in https://social.nil.im/objects/f3bd59bc-3411-4afc-873b-d90c52e95551

This works in MetaText.

**Comment by VyrCossont** [comment]
Was in fact fixed in the build I said it was going to be fixed in, but I forgot to close this.
