### ISSUE TITLE
[minor] shows Open registration even though it isn’t

### ISSUE THREAD

**Issue by mirabilos** [feditext/feditext#98]
On my GtS instance, I have registration disabled; the `/api/v1/instance` even shows `{ … "registrations":false, … }`. In the “About $my_instance” it shows them as open.

**Comment by VyrCossont** [comment]
Localization strings for two properties in the about this instance view were swapped. I have unswapped them. Should be fixed in the next build.

**Comment by mirabilos** [comment]
yes, fixed, thanks!
