### ISSUE TITLE
Major regression when posting images: unable to edit properties

### ISSUE THREAD

**Issue by mirabilos** [feditext/feditext#99]
**Describe the bug**
When attaching images to a new post, only black spacing is shown in the instance. It is not possible to edit the description or centre.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new post
2. Write something
3. Attach an image (if you can even find the paperclip icon, in one attempt just now it was hidden but tapping the space where it usually is worked)
4. Just black spacing is shown, see screenshot

**Expected behavior**
As in MetaText, I can edit description and centre of the image

**Screenshots**
![IMG_2340](https://github.com/feditext/feditext/assets/861078/48679bbd-5b85-464c-8c72-1a596cc868cb)

**(please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.7.6
 - App Version: 1.7.2 (48)

**Additional context**
Incidentally, the following works:

- post without doing anything to the images
- click “…” then “Delete & re-draft”
- then the expected things are there and work
- however, even there, adding or deleting an image will cause the same problems (e.g. deletions are not shown, the image stays there, but after posting, it’ll be gone)

I reported this via Testflight as well.

**Comment by VyrCossont** [comment]
Thanks. I think I know what caused this and it would have been in the last commit. Should be able to patch it in the next.
